### ISSUE TITLE
How to popInitialUrl?

### ISSUE THREAD

**Issue by kfiroo** [BranchMetrics/react-native-branch-deep-linking#100]
Hey,
Was wondering what is the right way to achieve the same as `ReactNative.Linking.getInitialURL()`?

Thanks

**Comment by jdee** [comment]
Hi @kfiroo. I think you're looking for [getFirstReferringParams](https://github.com/BranchMetrics/react-native-branch-deep-linking#getfirstreferringparams-promise), e.g.

```js
import branch from 'react-native-branch'

let params = await branch.getFirstReferringParams()

for (var property in params) {
  console.log(property + ": " + params[property])
}
```

**Comment by kfiroo** [comment]
@jdee thanks for your response!
I'm currently using it, the problem is it only works for branch links, I was wondering if that's by design?
I ended up having to use `getInitialUrl` as a fallback for `getFirstReferringParams`
Something like this:
```jsx
branch.getLatestReferringParams()
    .then(params => {
        if (params && params['+clicked_branch_link']) {
            return params;
        }
        return Linking.getInitialURL()
            .then(url => {
                return url ? {url} : null;
            });
    })
    .then(params => {
        if (!params) {
            // we did not arrive from a deep link
        }
        const intialUrl = params['$canonical_url'] || params.url;
        // do something with initialUrl...
    });
```

Also, I think subscribe acts the same and doesn't trigger for non branch links

Thanks

**Comment by kfiroo** [comment]
@jdee Turns out the problem was with the iOS configuration!
Everything seems to work fine now :)
Thanks!
