### ISSUE TITLE
`branch.subscribe` only works for branch urls

### ISSUE THREAD

**Issue by kfiroo** [BranchMetrics/react-native-branch-deep-linking#102]
Hey,
After some trouble with setting up my configuration properly (which I think I finally nailed down :) ) I have a strange behaviour in iOS.

When the application is running in the background and I click a non branch url `https://myapp.com/content/path` the app starts and I can see `continueUserActivity` in called in `AppDelegate.m`.

`BOOL handledByBranch = [RNBranch continueUserActivity:userActivity];`
`handledByBranch` is `YES`.

I added my domain to `branch_universal_link_domains` in our `plist`.

`branch.subscribe` callback is also called but with `null` for `params`, `uri` and `error`

I'm trying not to use `Linking.addEventListener('url', this.handleOpenURL);` here.

Any advice?

**Comment by kfiroo** [comment]
UPDATE: I see that the `branch.subscribe` callback is called with null values even when restoring the app from background manually (not by clicking a link) which leads me to think that the callback is never called for non branch links.

@jdee any ideas?

**Comment by kfiroo** [comment]
On android I managed to handle all incoming links using only `branch.subscribe`
My code looks like this:
```jsx
branch.subscribe(({params, uri, error}) => {
    if (error) {
        console.error(error);
    } else if (params) {
        // branch urls
    } else if (uri) {
        // non-branch urls
    }
    // not sure
});
```

Would be awesome to be able to have the same thing running on iOS

**Comment by jdee** [comment]
@kfiroo I'm glad you were able to solve some of your problems. In short, I think the behavior you're seeing on Android is unintentional. I think what you're trying to do makes a lot of sense, but it requires a little research for us to get it right in a future release. At the moment, what you want to do just won't work, at least not consistently. You're best off sticking with the two-stage approach you have until we can integrate properly.

The `uri` argument should only be populated if the link is a custom URI, not a Universal Link or App Link. If it's being populated with App Links to your domain on Android, that may mean that the two unintentionally share a code path. Perhaps you're using the same intent receiver for both, but I'm speculating.

On iOS, you'll need to do something like:

```Obj-C
// Respond to URI scheme links
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  return [RNBranch handleDeepLink:url] ||
     [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}

// Respond to Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
  return [RNBranch continueUserActivity:userActivity] || 
    [RCTLinkingManager application:application
              continueUserActivity:userActivity
                restorationHandler:restorationHandler];
}
```

This will ensure that the right layer (`ReactNative.Linking` or `react-native-branch`) is called for a given URI/URL.

In JavaScript, you'll have to call both `branch.subscribe` and `Linking.addEventListener`. I think the most sensible thing would be to have a separate code unit that handles URL routing and then pass the URLs from both these callbacks (the resolved URL from `params['$canonical_url']` or `params['$desktop_url']`, etc. in the case of Branch links) to the same place.

In the future, we can simplify this, but that's how it works in the current release.

**Comment by jdee** [comment]
@kfiroo Another option that could be simpler for you:

```js
callback = (event) => {
  var url = event.url
  if (!url) {
    // must be from Branch
    url = event.params ? event.params['$canonical_url'] : event.uri
  }

  if (!url) return // no URL found

  // now handle the URL, wherever it came from
}

Linking.addEventListener('url', callback)
branch.subscribe(callback)
```

**Comment by kfiroo** [comment]
@jdee Thanks!
Btw, I'll be happy to contribute in any way I can, let me know if you think I can help out :)

My iOS code looks very similar, i just have some Facebook integration code in there.

The javascript code is also very close to what you have here, only I noticed I sometimes get the `url` in `params['+non_branch_link']` is that expected?

I guess what confused me was this part of the docs `(both Branch & non-Branch)`
```jsx
// Subscribe to incoming links (both Branch & non-Branch)
// bundle = object with: {params, error, uri}
branch.subscribe((bundle) => {
  if (bundle && bundle.params && !bundle.error) {
    // grab deep link data and route appropriately.
  }
})
```

I was struggling to get the subscribe to work for all links, universal and app links.

**Comment by jdee** [comment]
@kfiroo Sorry for the delay. I think I was wrong about this. In fact, the `+non_branch_link` parameter is a supported feature, at least in the iOS SDK. I still have to test it out on Android. There are some changes required for the `+non_branch_link` parameter to make it through on iOS. I'll have something for you to try out soon. Sorry for the confusion.

**Comment by jdee** [comment]
@kfiroo If you have the chance, please try out the master branch (if you're using 1.0.x) or the maintenance-0.9 branch (if you're using 0.9.x). The `uri` field should show up for non-Branch links. What you had working for Android should work on iOS as well.

**Comment by kfiroo** [comment]
@jdee Amazing! Thanks for the quick response! :)
I'll test it out first thing tomorrow morning and let you know

**Comment by kfiroo** [comment]
@jdee Hey, I tested the changes on master on iOS and unfortunately it's still not working as expected :(
When clicking a non-branch url (`https://mydomain.com/path/to/content`) on both warm and cold starts (app is running in the background and app is completely closed respectively) trigger the `subscribe` callback with `{params: null, uri: null, error: null}`
