### ISSUE TITLE
How to send sms?

### ISSUE THREAD

**Issue by skleest** [BranchMetrics/react-native-branch-deep-linking#114]
Is it possible to use 'text me the app' function? 

For instance, if our app is running on iPad, then user can input his/her number to get a download link like: https://dev.branch.io/features/text-me-the-app/guide/#insert-sendsms-snippet-into-your-page.

Thank you.

**Comment by jdee** [comment]
Hi @skleest. Thanks for getting in touch.

I don't think this involves the RN SDK or any other mobile app SDK. (The JS calls in that snippet involve the Branch web SDK). It should work without any setup outside the Dashboard, unless you want to customize the HTML as discussed in the doc you shared. In that case, I think you host the custom HTML yourself. I haven't worked with this feature much myself, but I've seen the default page appear numerous times. If you have any trouble with it, please let us know details, and we'll assist.

**Comment by skleest** [comment]
Thanks for the fast answer @jdee! 
Yes, we've been working with the web landing page; was wondering if it would be possible to send to  users right from RN. Thanks again for the great component.

**Comment by skleest** [comment]
Hi @jdee,

Thanks for the further explanation! My use case was from sending from iPad (kiosk) to a phone, and since iPad does not have SMS capability, I thought I could take advantage of the function called from the desktop hosted page. It seems like I should generate the link then use Twilio to send it out!

Thanks!

**Comment by jdee** [comment]
@skleest There is one other option if you really want the SMS feature directly in your app. You can just use a WebView in the app and use an HTML/JS snippet like the one in the docs. This is a less standard approach, and it removes the other options from the share sheet. But if that's what you want, that also works.
