### ISSUE TITLE
expirationDate doesn't work

### ISSUE THREAD

**Issue by maxs15** [BranchMetrics/react-native-branch-deep-linking#115]
I tried to define the expirationDate property in my universalObject.
But I always get {$exp_date: 0, ...} when getting the link data.
Any idea what could be the issue ?

Thanks

**Comment by jdee** [comment]
Hi @maxs15. Which version of react-native-branch are you using? You need at least 0.9.1 (RN < 0.40) or 1.0.1 (RN >= 0.40). And is this iOS or Android or both? I'll take a look and see if there's an issue.

**Comment by maxs15** [comment]
Hey @jdee, Thanks for the help.
I'm currently on the 0.9.2, the issue is on IOS, didn't try on Android yet.

**Comment by jdee** [comment]
This seems to work for me. See the snippet below. One more question:

Do you see any output regarding expirationDate from Xcode? You might see the following messages which would account for this:

"expirationDate" is not supported by the installed version of the native Branch SDK for objects of type BranchUniversalObject. Please update to the current release using "pod update" or "carthage update".

Invalid expiration date format. Valid format is YYYY-mm-ddTHH:MM:SS, e.g. 2017-02-01T00:00:00. All times UTC.

This worked with Branch iOS SDK v0.13.5, react-native-branch v0.9.5 and react-native v0.39.2:

```js
let branchUniversalObject = branch.createBranchUniversalObject('canonicalIdentifier',
  {metadata:
    {prop1: 'test',
    prop2: 'abc'},
    title: 'Cool Content!',
    contentDescription: 'Cool Content Description',
    expirationDate: '2018-03-01T00:00:00'
  })

let shareOptions = { messageHeader: 'Check this out', messageBody: 'No really, check this out!' }
let linkProperties = { feature: 'share', channel: 'RNApp' }
let controlParams = { $desktop_url: 'http://example.com/home', $ios_url: 'http://example.com/ios' }
branchUniversalObject.showShareSheet(shareOptions, linkProperties, controlParams).then(({channel, completed, error}) => {
  if (error) {
    console.error("error from showShareSheet: " + error)
    return
  }

  console.info("share to channel " + channel + " completed: " + completed)
})
```

**Comment by maxs15** [comment]
Thanks for the help @jdee !
My pod wasn't up to date 👍
