### ISSUE TITLE
TypeError: Cannot read property 'setDebug' of undefined

### ISSUE THREAD

**Issue by jaimecorrea** [BranchMetrics/react-native-branch-deep-linking#119]
when running 'npm test' using jest

trace:

at new Branch (node_modules/react-native-branch/src/index.js:83:18)
at Object.<anonymous> (node_modules/react-native-branch/src/index.js:101:1)

**Comment by jdee** [comment]
@jaimecorrea Can you provide specifics of what you're doing with jest (changes to package.json, e.g.)? `npm test` succeeds when I run it, and it runs in CI for all commits and PRs. That error suggests that `RNBranch` is undefined, which means it's not finding the native module.
