### ISSUE TITLE
`messageBody` no longer supported?

### ISSUE THREAD

**Issue by gnestor** [BranchMetrics/react-native-branch-deep-linking#12]
In the previous version of this lib, the content of `messageBody` would be used when sharing via text messages for example, but now `contentDescription` is being used. I did a quick search in the repo and it looks like `messageBody` is only used for Android...

**Comment by rt2zz** [comment]
good catch, looks like a bug https://github.com/BranchMetrics/React-Native-Deferred-Deep-Linking-SDK/blob/master/RNBranch/RNBranch.m#L180 

Will resolve shortly

**Comment by gnestor** [comment]
Thanks!

**Comment by rt2zz** [comment]
done 👍

**Comment by rt2zz** [comment]
https://github.com/BranchMetrics/react-native-branch-deep-linking/commit/f8df69d792fe58916b268f149aeed9cc6bd7a75d
