### ISSUE TITLE
Updating to 1.1.0 does not compile for iOS

### ISSUE THREAD

**Issue by tomauty** [BranchMetrics/react-native-branch-deep-linking#128]
Shows missing header:
`<Branch/BranchConstants.h>`

I'm using Carthage to update the SDK, and it's also not present in the generated framework. Let me know if you need more info. This bug is not present in 1.0.5.

**Comment by jdee** [comment]
Hi @tomauty. Sorry for the trouble. Obviously not enough testing was done before this release went out. Are you able to try the master branch now? That should fix this issue. I'll push this release out later today, but it would be nice to confirm. Thanks.

**Comment by jdee** [comment]
Fixed in Version 1.1.1.
