### ISSUE TITLE
TransformError: src/index.js Unexpected token ...

### ISSUE THREAD

**Issue by alvingarcia** [BranchMetrics/react-native-branch-deep-linking#13]
Using 0.1.1
Didn't encounter this from 0.0.8. Did I miss something?

![error](http://i.imgur.com/f1zvOtu.png)

Installed using the ff.:
1. `npm install --save react-native-branch`
2. `rnpm link react-native-branch`
3. Add `pod 'Branch'` to your ios/Podfile
4. `cd ios && pod install`

**Comment by rt2zz** [comment]
what version of react-native are you on? 

Looks like your babel does not support spread operator which is odd. Do you have a custom .babelrc file?

**Comment by alvingarcia** [comment]
React-native: 0.24.0
No .babelrc file

**Comment by rt2zz** [comment]
@alvingarcia any progress with this? it sounds like your node_modules are not being transformed.

Still waiting for consensus to develop in the react-native about wether or not to precompile react-native modules...

**Comment by alvingarcia** [comment]
@rt2zz yes, it is not being transformed.

Unfortunately, I don't have the time able to look into it. So far, we haven't encountered any problem with the hack on production.

**Comment by rt2zz** [comment]
👍  please reopen if / when you want to dig in deeper
