### ISSUE TITLE
Subscribe param not an object?

### ISSUE THREAD

**Issue by dwilt** [BranchMetrics/react-native-branch-deep-linking#156]
[In the documentation example](https://github.com/BranchMetrics/react-native-branch-deep-linking#usage) for `subscribe`, you have this:

```js
branch.subscribe((bundle) => {
  if (bundle && bundle.params && !bundle.error) {
  	// grab deep link data and route appropriately.
  }
})
```
The `if` is checking if `bundle exists`, then checking if `bundle.params` exists (while also checking that an error doesn't exist). Is there a reason that your checking if bundle exists in the first place? This tells me that there are times when the callback is firing and the params might not always be an object.

This reason I'm asking about this is we are seeing an error in our app with a message `null is not an object (evaluating 'e.params')`.  This is how we are using `subscribe`:
```js
branch.subscribe(({ params }) => {
  if (params) {
    handleAction(params);
  }
});
```
This shorthand, [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) will error if what it's trying to destructure is not an object.. hence why I'm asking about your verbose `if` statement...

Also, is there ever a scenario when `params` would be an object and a value but there would also be an error?

**Comment by jdee** [comment]
@dwilt Which version of react-native-branch is generating this error?

Yes, destructuring assignment is a nicer way to handle this. I don't think that bundle can ever be undefined or null here, so that `if (bundle)` is unnecessary, as you point out. There are three parameters passed back to the subscribe callback. You could do this:

```js
branch.subscribe(({error, params, uri}) => {
  if (error) {
    // there was an error. this is a String
    return
  }

  if (params) {
    // this is an Object with the Branch params if it's nonnull
  }

  if (uri) {
    // This is a String with the original URI handled by the app, before passing off to the Branch SDK.
  }
})
```

I'm not sure when you would get anything but an Object for params, but I'll review.

**Comment by dwilt** [comment]
I'm not 100% sure it was Branch but the error looked like it. We're still dealing with sourcemap issues on our side (else this would be really obvious).

The version we are currently using is `1.0.4`.
