### ISSUE TITLE
[iOS] Shared link in FB app takes me to app store, not app itself

### ISSUE THREAD

**Issue by kyo504** [BranchMetrics/react-native-branch-deep-linking#157]
### Application Information
- Platform : iOS
- Branch : 1.1.0
- React Native : 0.41.2

### Issue Description
In case of iOS, when I click shared link in Facebook app, the link takes me to the app store even if app is already installed. Could you give any hint of this? Here is the link `https://feedyourmusic.app.link/JYfMF1nHfC`.
And here is a code snippet.
```javascript
  async componentDidMount() {
    const { trackInfo } = this.props;

    // Create BUO and register view event when view is displayed.
    this.branchUniversalObject = await branch.createBranchUniversalObject(`track/${trackInfo.id}`, {
      title: trackInfo.title,
      contentDescription: trackInfo.request_msg,
      contentImageUrl: getArtworkURL(trackInfo.artwork_url, IMAGE_SIZE.SC.CROP),
      metadata: {
        resource: 'song',
        songId: `${trackInfo.id}`,
      },
      automaticallyListOnSpotlight: true,  // for iOS
    });
    this.branchUniversalObject.userCompletedAction(RegisterViewEvent);
  }
  ...
  async onPressShare(id) {
    const controlParams = {
      $desktop_url: `${TRACK_SHARE_URL}${id}`,
      $android_url: PLAYSTORE_URL,
      $ios_url: APPSTORE_URL,
    };
    const linkProperties = { feature: 'Share', channel: 'FeedYourMusic' };
    const { url } = await this.branchUniversalObject.generateShortUrl(linkProperties, controlParams);

    this.branchUniversalObject.userCompletedAction(ShareInitiatedEvent);
    Share.share({
      title: '[피드유어뮤직] 곡 공유',
      message: url,
    })
      .then(() => {
        this.branchUniversalObject.userCompletedAction(ShareCompletedEvent);
      })
      .catch(error => Actions.error({ error: error.message }));
  }
```

**Comment by kyo504** [comment]
Or you could download my app if you see the problem
### Steps to reproduce
1. Install app (Searching `feedyourmusic` or `피드유어뮤직` in app store)
2. Lauch app
3. Share any music to facebook
4. Open facebook app and click the shared link

**Comment by jdee** [comment]
@kyo504 Sorry to hear this isn't working. I can reproduce the problem. I installed the app and can open the test link in the app, so your Universal Links must be configured correctly. When I share to Facebook and open the link in the iOS FB app, it shows a Branch Deepview in a webview and tries to go to the App Store.

I think this is a known issue with the Facebook app. If you add a `$ios_deepview` control parameter, you can improve the behavior, e.g.:

```js
    const controlParams = {
      $desktop_url: `${TRACK_SHARE_URL}${id}`,
      $android_url: PLAYSTORE_URL,
      $ios_url: APPSTORE_URL,
      $ios_deepview: 'branch_default'
    };
```

Then the FB app will no longer try to open the AppStore if your app is installed. It will show the Deepview in a webview. The "Get The App" button at the bottom will open the app directly if it is installed.

**Comment by kyo504** [comment]
@jdee Thanks for the investigation. Now it works fine. If it's a known issue with FB app, could branch team handle this issue and any plan for this? Or should I keep this mechanism in case of FB app?

**Comment by jdee** [comment]
@kyo504 This is Branch's workaround for the issue. I'm not sure what more Branch can do. There are a number of limitations imposed by iOS. I would recommend keeping the $ios_deepview setting or just enabling Deepviews in the Dashboard.

**Comment by kyo504** [comment]
Thanks for the explanation. I got your point. :)
