### ISSUE TITLE
Add fabric to maven repositories?

### ISSUE THREAD

**Issue by rt2zz** [BranchMetrics/react-native-branch-deep-linking#16]
After the [recent build.gradle updates](https://github.com/BranchMetrics/react-native-branch-deep-linking/commit/9d2cbca9d927fca7df48bffe12c7a387cab64458) I now get an error:
```
A problem occurred configuring project ':react-native-branch'.
   > Could not resolve all dependencies for configuration ':react-native-branch:_debugCompile'.
      > Could not find com.crashlytics.sdk.android:answers:1.3.6.
```

adding `maven { url 'https://maven.fabric.io/public' }` to the repositories fixes this.

Is crashalytics required for branch sdk? If so I assume the best solution is to add the fabric repo to the module's build.gradle.

cc/ @aaustin

**Comment by sojanpr** [comment]
@rt2zz we just updated a fix for this issue in the Android SDK. Will be available shortly from maven.  Could you please refresh  your build and try again after a few minutes

**Comment by aaustin** [comment]
We're working on a cleaner solution, but in the meantime, Zack, can you update the React lib to use the locked version of 1.13.1 of Android? I.e. `compile ('io.branch.sdk.android:library:1.13.1')`

**Comment by rt2zz** [comment]
done and testing, will cut a new release shortly

**Comment by aaustin** [comment]
Thank you sir - this has caused us quite the headache today 😫
