### ISSUE TITLE
Android app won't start after linking module

### ISSUE THREAD

**Issue by andreibarabas** [BranchMetrics/react-native-branch-deep-linking#183]
Steps to reproduce:
- link the 2.x-beta1 module
- simply run react-native run-android 

you will see the app won't start (and will create a crash).

See here the installed modules:

> "dependencies":
> 
>  {
>     "immutable": "^3.8.1",
>     "merge": "^1.2.0",
>     "merge-recursive": "0.0.3",
>     "native-base": "^2.0.10",
>     "path": "^0.12.7",
>     "qs": "^6.3.0",
>     "react": "15.4.2",
>     "react-native": "^0.41.0",
>     "react-native-action-button": "^2.6.4",
>     "react-native-branch": "^2.0.0-beta.1",
>     "react-native-fabric": "^0.4.1",
>     "react-native-fabric-digits": "github:jeanlebrument/react-native-fabric-digits",
>     "react-native-fs": "^2.1.0-rc.1",
>     "react-native-intercom": "git://github.com/andreibarabas/react-native-intercom.git#v5.8.0-with-intercom-v3.1",
>     "react-native-locale": "0.0.15",
>     "react-native-material-design": "^0.3.7",
>     "react-native-onesignal": "git://github.com/andreibarabas/react-native-onesignal.git#v3.0.3-with-updated-ios-sdk-v2.5.2",
>     "react-native-pdf-view": "git://github.com/cnjon/react-native-pdf-view.git#9c759f47af76a5123c8177ac23376849e52f1d7b",
>     "react-native-router-flux": "^3.37.0",
>     "react-native-swiper": "^1.5.4",
>     "react-native-vector-icons": "^4.0.0",
>     "react-redux": "^5.0.2",
>     "redux": "^3.6.0",
>     "redux-thunk": "^2.2.0",
>     "tcomb-form-native": "^0.6.4",
>     "url": "^0.11.0",
>     "util": "^0.10.3"
>   },

and

> dependencies {
>     compile project(':react-native-intercom')
>     compile project(':react-native-locale')
>     compile project(':react-native-fabric-digits')
>     compile project(':react-native-fabric')
>     compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
>         transitive = true;
>     }
>     compile('com.digits.sdk.android:digits:2.0.5@aar') {
>         transitive = true;
>     }
>     compile project(':react-native-pdf-view')
>     compile project(':react-native-vector-icons')
>     compile fileTree(dir: "libs", include: ["*.jar"])
>     compile "com.android.support:appcompat-v7:23.0.1"
>     compile "com.facebook.react:react-native:+"  // From node_modules
>     compile project(':react-native-fs')
>     compile project(':react-native-onesignal')
> }

**P.S:** I've even trying simply adding the Android SDK (without any react native wrapper) and again, won't start. Is there a conflict with Fabric?

**Comment by jdee** [comment]
Hello @andreibarabas. Sorry you're having this problem. A few questions:

- Can you share the actual error output? 
- Does the error occur at build time or runtime? 
- Are you using the Branch/Fabric integration? 
- Did you already have react-native-fabric in your app, or are you just adding that now?

I have a small problem when I do this:

```bash
react-native init AndroidCrashProject
cd !$
npm install --save react-native-fabric
npm install --save react-native-branch
react-native link react-native-fabric
react-native link react-native-branch
```

Now the Android project will not build until I add `maven { url 'https://maven.fabric.io/public' }` to the project's build.gradle:

```
allprojects {
    repositories {
        mavenLocal()
        maven { url 'https://maven.fabric.io/public' } // <= Added this
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

Once I add that, it builds and runs just fine, either through Android Studio or using `react-native run-android`. I haven't set up either Fabric or Branch correctly in the app, but it sounds like you're having trouble either when building or at application launch.

Here's the package.json:

```json
{
  "name": "AndroidCrashProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "15.4.2",
    "react-native": "0.41.0",
    "react-native-branch": "^2.0.0-beta.1",
    "react-native-fabric": "^0.4.1"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by andreibarabas** [comment]
Hi @jdee . Thanks for the reply. In the meantime I managed to figure out that no matter what plugin I would add, it did not work. It seems we reached the [64k Android Method Limit](https://developer.android.com/studio/build/multidex.html), and thus we simply had to switch to Multiple Dex files. 


You can close the issue. Thanks!

**Comment by jdee** [comment]
I'm glad you found the problem. Closing.
