### ISSUE TITLE
Could you please provide Swift initialization documentation?

### ISSUE THREAD

**Issue by guysegal** [BranchMetrics/react-native-branch-deep-linking#191]

**Comment by jdee** [comment]
Thanks for bringing this up. I've added a Swift section: https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/setup.md#swift. We'll get this into the docs site as well.

**Comment by jdee** [comment]
Also note there is a working Swift example in this repo: https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example_native_ios/WebViewExample/AppDelegate.swift. This is a native Swift app with a RN component included, so the structure is slightly different. The RCTRootView is added in the ArticleViewController, not the AppDelegate. But the Branch initialization calls are the same in both cases.
