### ISSUE TITLE
Delay getting opening deeplink and subscribe triggers action twice

### ISSUE THREAD

**Issue by pawlowskim** [BranchMetrics/react-native-branch-deep-linking#197]
Hi. I'm switching from previous deeplink service I was used for a while to branch.io. 

In my case, I need to delay opening deeplink action until app is fully initialised and user is possibly logged in. So, I would like to know, is there any option to manipulate subscribe initial ttl time? I have a service that subscribes when it's created and I call manually checking last deeplink when application is initialised. In that case, deeplink most of the time is triggered twice, because subscribe method get's the deeplink from which app was opened, it triggers and then manually check is triggered again. In case, where initialisation will last longer, subscribe will not trigger my action and only manual check will do the thing. 

For workaround I could store id of last deeplink on the JS side, and manually check if they are different, but this is ugly solution and I would rather set ttl time to 0, so subscribe will never hook first deeplink (deeplink which opens the application).

Hope you understand what I mean :P
Cheers.

**Comment by jdee** [comment]
Hi @pawlowskim. As of version 2.0.0-beta.3, you can do this:

```js
import branch from 'react-native-branch'
branch.initSessionTtl = 0
```

This was introduced for testing, but it also offers you a back door in case the default value doesn't work for your app. This is used in certain unit tests to pretend that the TTL has expired and ensure that in that case the cache is not consulted, so no cached value can be returned.

**Comment by pawlowskim** [comment]
I will test it tomorrow and let u know. Thanks in advance :)

**Comment by pawlowskim** [comment]
@jdee Works like a charm. Thx :)
