### ISSUE TITLE
[iOS] Production build doesn't open application

### ISSUE THREAD

**Issue by pawlowskim** [BranchMetrics/react-native-branch-deep-linking#198]
Hello again :)

I have integrated branch on both iOS and Android. On Android everything seems to works fine, but on iOS I have one more issue to solve.

I read :
1. https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/110
2. https://github.com/BranchMetrics/ios-branch-deep-linking/issues/604
3. https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/158

and according to above, I don't need to have production build installed through AppStore to make it work. For test build with test branch key it works like a charm. I can open application if it's installed, redirect to AppStore if it's not, open context menu in mail application and see that I can open It in my app (AD. 1).
For production build non of above works. It works the same way as it's described AD. 1: "(...)However, after returning to app manually, callback was firing(...)". 

I have configured Universal Links, I'm always using Deepview and can't figure it out what is wrong. For testing I use this link generator:
```
curl -X POST \
\
-H "Content-Type: application/json" \
\
-d '{"branch_key":"my_life_key", "data":"{my_custom_data, \"$ios_deepview\":\"branch_default\", \"$android_deepview\":\"branch_default\", \"$og_title\":\"my title\", \"$og_description\":\"my desc\"}"}' \
\
https://api.branch.io/v1/url
```

Any thoughts?

**Comment by jdee** [comment]
Hi @pawlowskim. If the context menu option in the Mail (or Notes or Messages) app on iOS does not work, then it usually means that the domain association is not correct. Does the option appear to `Open in "My App" App`? If that doesn't appear at all, then it's probably an issue with the configuration in the Branch Dashboard. If that option appears but doesn't work, it might be something else.

There are four things that have to agree in the app and the Dashboard:

- The Branch key: Must be correct in the Info.plist
- The Branch domain(s): Your domains should all be listed in your associated-domains entitlement (Using the Capabilities tab). 
  + If you're using an app.link subdomain, you need:
    - `applinks:myapp.app.link`
    - `applinks:myapp-alternate.app.link`
    - `applinks:myapp.test-app.link`
    - `applinks:myapp-alternate.test-app.link`
  + If you're using a custom domain, you just need:
    - `applinks:customdomain.com`
- The bundle identifier for your app: Make sure the setting in the Dashboard is correct for both live and test keys.
- Your team signing ID: Make sure the setting in the Dashboard is correct for both live and test keys.

Note that the bundle and team identifiers may be set differently for the live and test environment. Possibly you have them set correctly for test but not live. 

If you think all this is correct, can you share an example link that fails to open the app? Or even just tell me your domain? I might be able to spot an obvious problem there.

**Comment by pawlowskim** [comment]
Very strange :/ Yesterday, I had wrong Apple App Prefix I changed it. Then tried production build and it didn't work. I checked everything twice and still nothing. Today I checked again every single point you mention, did not change anything in my configuration (nor Branch dashboard, nor mobile) and it automagically start working o_O. Does branch need some time to reload or something after changing Apple App Prefix? 

Few more question:
1. From the Deepview, button on the bottom "Open the App" should take me to the application or to the AppStore (I can see open in my app from context menu when hold a button for a while)? 
2. There is popup on the top of the Deepview with application name and button "Open" that open the App. Is there any way to make this popup visible immediately? User needs to scroll down a little to make it visible.

**Comment by jdee** [comment]
Hi @pawlowskim. I'm glad it started working. Changes in the Branch Dashboard should be immediate. If you have trouble like this again, here's another thing you can always check. The Dashboard is where you enter the information, but what matters is the [apple-app-site-association](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html) file for the domain. Branch generates this from the information you enter in the Dashboard. For example, my test domain is `l1mv.app.link`. The AASA file is here: https://l1mv.app.link/apple-app-site-association. The contents of that file are:

```json
{"applinks":{"apps":[],"details":[{"appID":"RAARD2VX57.info.dubsar.TestBed-ReactNative","paths":["NOT /e/*","*","/"]}]}}
```

That is my team signing ID and a bundle identifier I use for testing. The rest will always be the same for app.link domains. You can always look at that file on your domain to see what the parameters are, but they should always be whatever is in the Dashboard for the live or test domain. iOS checks that file whenever an app is installed, including when you deploy from Xcode. If you make changes to the AASA file (Branch Dashboard) you may have to reinstall the app. Maybe that explains the mystery?

Other questions:
1. The Open the App button in the Deepview is just a universal link and will open the app if it is installed or take the user to the App Store ($ios_url) if not. (Or they can use the context menu to choose one or the other as you mentioned.)
2. I think you're talking about the iOS Smart App Banner in Safari (see the [Universal Links documentation](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html)). You have to pull the page down to see it. This is generated by iOS/Safari, not Branch. This is always available for any UL domain and not part of the Deepview. I've also thought it's a shame that it doesn't appear automatically. I think Apple's motive is that they don't want to affect the layout of the website. At any rate, this is Apple's UI, and I don't know of any way to change it.
3. I know that you can, but I don't know how. I think if you look at [Configuring Links](https://dev.branch.io/getting-started/configuring-links/guide/) in the docs site, you'll find it. All these questions are kind of general and don't have much to do with RN or this repo, so I'm getting out of my depth. If you want good answers to questions like this, you should contact integrations@branch.io or open a support ticket through the Support link in the Dashboard.

**Comment by pawlowskim** [comment]
Thanks for your response. If I have any other problems I will create a new topic. 
For the 3rd question I mentioned: It's necessary to add flag: {"type": 2} next to branch_key.
