### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by guysegal** [BranchMetrics/react-native-branch-deep-linking#20]
Is Swift version planned?

**Comment by rt2zz** [comment]
No swift plans. How would a swift version help your use case? Presumably that is just an implementation detail.

**Comment by guysegal** [comment]
We have a Swift project with react native and we're having hard time compiling it with obj c library

**Comment by guysegal** [comment]
I added the pod to the Podfile: 
```
target 'MyProject' do
  pod 'React', :path => '../node_modules/react-native'
  pod 'react-native-branch', :path => '../node_modules/react-native-branch'
end
```
but when I compile the project I get this error:
<img width="664" alt="screen shot 2016-07-05 at 9 06 05 am" src="https://cloud.githubusercontent.com/assets/7164560/16575307/dfe75380-428f-11e6-9eab-613e8d343c3a.png">

What am I doing wrong?

BTW - shouldn't react-native-branch podspec contain dependency on React pod?

**Comment by rt2zz** [comment]
Added to podspec in #22 

Will cut a new npm release tomorrow.

Thanks 👍
