### ISSUE TITLE
[iOS] - branch.subscribe not running when app starts

### ISSUE THREAD

**Issue by seque1990** [BranchMetrics/react-native-branch-deep-linking#211]
I have something like this my iOS application:

```

    componentWillMount () {
      branch.subscribe(({ params }) => {
        if (params) {
          const objectScene = params['object']
          if(objectScene === 'Quote') {
            const bookID = params['bookID']
            navigator.push(getQuotesRoute(bookID))
          } else if (objectScene === 'Book') {
            const bookID = params['bookID']
            navigator.push(getBookRoute(bookID))
          } else if (objectScene === 'Shelf') {
            const shelfID = params['shelfID']
            navigator.push(getLibraryRoute(shelfID))
          }
        }
      })
      ....
```

The problem happens when I click a a branch link with the app closed, and the branch subscribe function never starts running. 

If I however, have the App in the background and click in the branch link the branch.subscribe function starts running and everything works as expected. I'm not sure if this problem is related with the configuration or anything else.

**Comment by jdee** [comment]
Hi @seque1990. Sorry for the delay. I thought I answered this last week.

I'm not sure why that would happen, but there are two things I would check:

In the AppDelegate, when you call `[RNBranch initSessionWithLaunchOptions:isReferrable:]`, be sure the launch options are being passed:

```Obj-C
    [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];
```

```Swift
    RNBranch.initSession(launchOptions: launchOptions, isReferrable: true)
```

If this is not the problem, it is possible that the initial link is timing out before your JS finishes loading. You can try setting `branch.initSessionTtl` in your initialization code. By default it is 5000 ms. After that length of time, the initial link will not be returned to `branch.subscribe`. This is done to support unsubscribing and resubscribing, so the initial link will not be returned later if you resubscribe. Try setting `branch.initSessionTtl` to some larger number (in ms).

You can also refer to `webview_example` in this repo, which handles the initial link properly.

**Comment by seque1990** [comment]
Hello @jdee,

1. I do have this information in AppDelegate,

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];

  NSURL *jsCodeLocation;
  
  ...
```

I think, that's the proper way to have it.

2. Also in the initialization code, I tried with the following and had the same result.

```
import branch from 'react-native-branch'
branch.initSessionTtl = 10000
``` 

I don't know if it could be related, but we currently have 

`react-native-branch 0.8.0`
`react-native 0.34.1`

**Comment by jdee** [comment]
@seque1990 Thanks for the info. That is the right way to call the initialization method in Obj-C.

`branch.initSessionTtl` was introduced in 2.0. 1.0 and higher require RN 0.40. You can at least update to 0.9.6 and see if that helps.

It's getting harder to support < 0.40. Do you have any plans to update to RN 0.40? These docs will give you some advice:

https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/updating-1.0.0.md
https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/Release-2.0.0.md#existing-apps-updating-to-20

**Comment by maxcodes** [comment]
Hey all, I took over @seque1990 for the same project, and I've figured it out.

iPhone 6s, running iOS 10.3.2

1. Upgrade React Native to 0.40.0
2. Upgrade react-native-branch to 2.0.0-beta.7 (including relinking the library, removing pod, namespaced imports, etc)
3. In AppDelegate.m you need to do a couple things:

```
// Make sure this method returns YES
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  / ...
  return YES; // this line is important
}

// Remove this method if you have it
(BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation { ... }

// Make sure this method is exactly as follows
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
  return [RNBranch continueUserActivity:userActivity];
}

// Make sure to add Branch at the bottom of this method
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
  // You might have some other integrations with fb and twitter here...
  // ...
  // Add this just before the "return NO"
    if ([RNBranch.branch application:app openURL:url options:options]) {
    return YES;
  }

  return NO;
}
```

The only thing still missing is getting the branch links from push notifications to work (We're using OneSignal). But it's probably a separate issue. 

Feel free to close this issue.
