### ISSUE TITLE
Crash on iphone 5: EXC_SOFTWARE / UNCAUGHT_NS_EXCEPTION

### ISSUE THREAD

**Issue by minhtc** [BranchMetrics/react-native-branch-deep-linking#212]
Many iphone 5 users crashed by the same issue as in attachment screenshot.
I don't have any real device but it works fine on iphone 5 simulator. 
Anyone experienced this issue? Any suggestions on this issue?
Many Thanks

> -[BranchUserCompletedActionRequest makeRequest:key:callback:] + 3237935

![alt text](http://i.imgur.com/qnGHRpg.png "Sentry Logs")

![alt text](http://i.imgur.com/SZ3fYgA.png "Firebase ")

**Comment by jdee** [comment]
This is presumably happening when you call either `branch.userCompletedAction` or `branchUniversalObject.userCompletedAction`. Are you passing custom parameters? Can you share an example of how you're calling the method in JS? Are you passing an array as a custom parameter? I'll see if I can determine what else might cause this.

**Comment by jdee** [comment]
Also, could you please provide the versions you're using of `react-native-branch` and `react-native`?

**Comment by minhtc** [comment]
I can't reproduce this issue but received from firebase crash analytics.
I use the latest version: "react-native-branch": "^2.0.0-beta.5" + "react-native": "0.44.1" + "pod Branch (0.15.3)"

**Comment by jdee** [comment]
Hi @minhtc. Sorry for the delay. The line reported in the stack trace is here: https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/Requests/BranchUserCompletedActionRequest.m#L44. The error in the stack trace says that self.action is not an NSString but an NSArrayM (NSMutableArray). Obj-C type checking would report an error at compile time if the wrong data type were passed from another stack frame. The only place there is no type checking is in JavaScript. If you call:

```js
branchUniversalObject.userCompletedAction(["abc", "def"])
```

That will incorrectly pass an array from JS to Obj-C. But when I try that, I don't get a crash. I get a big red error screen in the app saying that the array cannot be converted to a string. It might be a good idea to verify that you're never passing an array as the first parameter in userCompletedAction.

Another thing that is strange is that you're using react-native-branch 2.0.0-beta.5 and also the Branch pod. The Branch SDK is now integrated into the react-native-branch library and should not be installed separately. If you updated from 1.x, you should remove the Branch pod. https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/Release-2.0.0.md#existing-apps-updating-to-20

2.0.0-beta.5 includes Branch SDK 0.14.12. 2.0.0-beta.6 includes 0.15.3. If you have both 0.14.12 in the react-native-branch module and 0.15.3 as a pod, it's possible that you could get this kind of problem. I would recommend correcting that, at least: update to 2.0.0-beta.6 and remove the Branch pod.

**Comment by minhtc** [comment]
@jdee Thank you so much for your clarification.
Actually I haven't dispatch any 'userCompletedAction()' action yet, seem like it was called somewhere automatically.
Anw, thank you for your time 👍
