### ISSUE TITLE
Jest errors when using react-native-branch

### ISSUE THREAD

**Issue by rickardinho** [BranchMetrics/react-native-branch-deep-linking#217]
I'm getting an issue when my jest tests run, even though everything seems to work fine in my app.
I'm getting jest errors like these:

Test suite failed to run
 
    TypeError: Cannot read property 'ADD_TO_CART_EVENT' of undefined
      
      at Object.<anonymous> (node_modules/react-native-branch/src/index.js:9:51)
      at Object.<anonymous> (src/js/lib/branchLink.js:87:111)
      at Object.<anonymous> (src/js/actions/create.js:142:198)

This seems to be caused by branch, but I'm not using ADD_TO_CART_EVENT anywhere in my code.  How can i fix this?

**Comment by jdee** [comment]
I think the best thing here is to mock Branch in your tests and not actually use the module in your testing. I don't have a lot of insight into that process for you, unfortunately. One of my to-dos is to convert the tests in this module to jest from ava. In the process, I may be able to come up with an easy mock solution you can just import into your tests.

For now, you can borrow the RNBranch and RNBranchEventEmitter mocks from the repo tests: https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/test/helpers/RNBranch.mock.js#L5.

**Comment by rickardinho** [comment]
So to mock Fabric I used code like this:

jest.mock('react-native-fabric', () => {
  return {
    Crashlytics: {
      crash: () => {}
    },
    Answers: {
      logCustom: () => {},
      logContentView: () => {}
    }
  };
});

What would be the equivalent for Branch?
Sorry, i didn't understand the example.

**Comment by jdee** [comment]
Here is one other dev's solution: https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/161#issuecomment-294294004

The problem is I'm not very familiar with jest. That's why I can't offer very good advice. But based on what you have there, you could try something like:

```js
jest.mock('react-native-branch', () => {
  return {
    AddToCartEvent: "Add To Cart",
    // etc.

    subscribe: (cb) => { cb({params: {}, error: null}) }
    // and for createBranchUniversalObject, etc.
  }
});
```

But I'm not sure of the details there. It may require some trial and error.

The other thing you could do is add something like the contents of RNBranch.mock.js. You might have to mock other methods on RNBranch, depending on what you're testing. This will definitely fix the immediate problem, but your unit tests will actually call react-native-branch, so bugs in this SDK may show up as bugs in your unit tests. You're better off with an approach like the above if you can get the details right.

```js
import React from 'react-native'

const defaultSession = {params: {}, error: null}

React.NativeModules.RNBranch = {
  // Mock constants exported by native layers
  ADD_TO_CART_EVENT: 'Add to Cart',
  ADD_TO_WISHLIST_EVENT: 'Add to Wishlist',
  PURCHASE_INITIATED_EVENT: 'Purchase Started',
  PURCHASED_EVENT: 'Purchased',
  REGISTER_VIEW_EVENT: 'View',
  SHARE_COMPLETED_EVENT: 'Share Completed',
  SHARE_INITIATED_EVENT: 'Share Started',

  redeemInitSessionResult() {
    return new Promise((resolve, reject) => {
      setTimeout(() => resolve(defaultSession), 500)
    })
  }
}

// This only has to exist to be passed to the NativeEventEmitter
// constructor.
React.NativeModules.RNBranchEventEmitter = {
}

```

**Comment by danielmartinprieto** [comment]
Hi! Just experienced this issue myself, but I’m not entirely happy with the solution proposed. The problem is that I don’t understand why should I mock parts of the SDK that I’m not using, so I’m probably missing something important regarding how Branch works. Could anyone help me with this?

**Comment by fatlinesofcode** [comment]
this worked for us
```
jest.mock('react-native-branch', () => {
  const REACT_NATIVE = jest.requireActual('react-native')
  REACT_NATIVE.NativeModules.RNBranch = {
    logEvent: jest.fn(() => true),
    STANDARD_EVENT_ADD_TO_CART: 'ADD_TO_CART'
  }
  const actualModule = jest.requireActual('react-native-branch')
  const mockedModule = {
    __esModule: true,
    ...actualModule,
    BranchEvent: jest.fn().mockImplementation((...args) => new actualModule.BranchEvent(...args))
  }

  mockedModule.BranchEvent.ViewCart = 'VIEW_CART'
  mockedModule.BranchEvent.InitiatePurchase = 'INITIATE_PURCHASE'
  mockedModule.BranchEvent.AddToCart = 'ADD_TO_CART'
  mockedModule.BranchEvent.Purchase = 'PURCHASE'
  mockedModule.BranchEvent.ViewItem = 'VIEW_ITEM'
  mockedModule.BranchEvent.CompleteRegistration = 'COMPLETE_REGISTRATION'
  mockedModule.BranchEvent.Login = 'LOGIN'
  mockedModule.BranchEvent.ViewItems = 'VIEW_ITEMS'
  mockedModule.default.createBranchUniversalObject = jest.fn((...args) => ({
    ident: 'MOCK-IDENT',
    ...args
  }))
  return mockedModule
})```

**Comment by manjuy124** [comment]
this worked for us

```
jest.mock('react-native-branch', () => {
	const REACT_NATIVE = jest.requireActual('react-native');
	REACT_NATIVE.NativeModules.RNBranch = {
		logEvent: jest.fn(() => true),
		STANDARD_EVENT_ADD_TO_CART: 'ADD_TO_CART',
		redeemInitSessionResult: jest.fn(() =>
			Promise.resolve({
				params: {
					'+clicked_branch_link': false,
					'+is_first_session': false,
				},
				error: null,
				uri: null,
			})
		),
		notifyNativeToInit: jest.fn(() => Promise.resolve({})),
	};
	const actualModule = jest.requireActual('react-native-branch');
	const mockedModule = {
		__esModule: true,
		...actualModule,
		BranchEvent: jest
			.fn()
			.mockImplementation((...args) => new actualModule.BranchEvent(...args)),
	};

	mockedModule.BranchEvent.ViewCart = 'VIEW_CART';
	mockedModule.BranchEvent.InitiatePurchase = 'INITIATE_PURCHASE';
	mockedModule.BranchEvent.AddToCart = 'ADD_TO_CART';
	mockedModule.BranchEvent.Purchase = 'PURCHASE';
	mockedModule.BranchEvent.ViewItem = 'VIEW_ITEM';
	mockedModule.BranchEvent.CompleteRegistration = 'COMPLETE_REGISTRATION';
	mockedModule.BranchEvent.Login = 'LOGIN';
	mockedModule.BranchEvent.ViewItems = 'VIEW_ITEMS';
	mockedModule.default.createBranchUniversalObject = jest.fn((...args) => ({
		ident: 'MOCK-IDENT',
		...args,
	}));
	return mockedModule;
});
```
