### ISSUE TITLE
No known class method for selector setRequestMetadataKey

### ISSUE THREAD

**Issue by zachrnolan** [BranchMetrics/react-native-branch-deep-linking#221]
I'm trying to implement Mixpanel with Branch using this code:

```
[RNBranch setRequestMetadataKey:[Mixpanel sharedInstance].distinctId];
```

It throws an error in xcode saying 
```
/PathToProject/AppDelegate.m:36:13: No known class method for selector 'setRequestMetadataKey:'
```

Not sure how to get around this. Any help is appreciated!

**Comment by zachrnolan** [comment]
Well never mind, mistake on my implementation of the call. For anyone else stuck, it should look like this:

```
[RNBranch setRequestMetadataKey:@"$mixpanel_distinct_id" value:[Mixpanel sharedInstance].distinctId];
```

**Comment by simistern** [comment]
I am having a similiar issue here, my code is as folows

`  [RNBranch setRequestMetadataKey:@"$segment_anonymous_id" value:[[SEGAnalytics sharedAnalytics] getAnonymousId]];
`

**Comment by ajmeersha** [comment]
I am having a similiar issue here, my code is as follows

   [RNBranch setRequestMetadataKey:@"$clevertap_attribution_id" value:[[CleverTap sharedInstance] profileGetCleverTapAttributionIdentifier]];

this is happening after updating to v5+
