### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by ceyhuno** [BranchMetrics/react-native-branch-deep-linking#224]
Are you planning to add TypeScript typings via https://github.com/DefinitelyTyped/DefinitelyTyped?

**Comment by jdee** [comment]
Sorry for the delay in answering. The short answer is no, no plans. But TypeScript is popular. We should be able to provide support.

**Comment by brunolemos** [comment]
That would be great.

**Comment by jinshin1013** [comment]
Is there any progress on this? I'm happy to help out with this one.

**Comment by sequoiaat** [comment]
Hello, 
We have this feature in our wishlist, but we don't have a plan to implement it soon. We will let you know once we plan to implement it. Thanks!

**Comment by 13thdeus** [comment]
For people who will search types:
Create file named "react-native-branch.d.ts" inside your "types" directory (%projectRoot%/src/types in my case) and paste this code into:
`/* tslint:disable */

declare module "react-native-branch" {
    interface IBranchUniversalObjectCreationOptions {
        canonicalIdentifier: string;
        title?: string;
        canonicalUrl?: string;
        contentDescription?: string;
        contentImageUrl?: string;
        locallyIndex?: boolean;
        publiclyIndex?: boolean;
        contentIndexingMode?: "private" | "public";
        currency?: string;
        price?: string;
        /**
         * format: yyyy-MM-dd'T'HH:mm:ss
         */
        expirationDate?: string;
        keywords?: string[];
        metadata?: any;
        type?: string;
        contentMetadata?: {
            contentSchema?: string;
            quantity?: number;
            price?: number;
            currency?: string;
            sku?: string;
            productName?: string;
            productBrand?: string;
            productCategory?: string;
            productVariant?: string;
            condition?: string;
            ratingAverage?: number;
            ratingCount?: number;
            ratingMax?: number;
            addressStreet?: string;
            addressCity?: string;
            addressRegion?: string;
            addressCountry?: string;
            addressPostalCode?: string;
            latitude?: number;
            longitude?: number;
            imageCaptions?: string;
            customMetadata?: any;
        };

    }

    export interface IBranchLinkInfo {
        "$canonical_identifier": string;
        "$canonical_url": string;
        "$desktop_url": string;
        "$exp_date": number;
        "$identity_id": string;
        "$og_description": string;
        "$og_image_url": string;
        "$og_title": string;
        "$one_time_use": boolean;
        "$publicly_indexable": string;
        "+click_timestamp": number;
        "+clicked_branch_link": boolean;
        "+is_first_session": boolean;
        "+match_guaranteed": boolean;
        "~campaign": string;
        "~channel": string;
        "~creation_source": number;
        "~feature": string;
        "~id": string;
        "~referring_link": string;
        "~stage": string;
        "~tags": string [];
    }

    export interface IBranchLinkProperties {
        feature: string;
        channel: string;
    }

    export interface IBranchControlParams {
        "$desktop_url"?: string;
        "$ios_url"?: string;
    }

    export interface IBranchShareOptions {
        messageHeader: string;
        messageBody: string;
    }

    export interface IBranchUniversalObject {
        ident: string;
        generateShortUrl: (linkProperties: IBranchLinkProperties, controlParams: IBranchControlParams) => Promise<{ url: string }>;
        showShareSheet: (shareOptions: IBranchShareOptions, linkProperties: IBranchLinkProperties, controlParams: IBranchControlParams) => Promise<{ channel: any, completed: any, error: any }>;
        listOnSpotlight: () => any;
        logEvent: (eventName: string) => any;
        registerView: (ident: string) => Promise<void>;
        release: () => void;
        userCompletedAction: (event: any) => any;
        _newIdent: () => any;
        _tryFunction: (func: any) => any;
    }

    class Branch {
        key = null;
        _checkCachedEvents = true;
        _debug = false;

        constructor(options: { debug?: boolean });

        subscribe(listener: (params: { error: any, params: any }) => void): () => void;

        skipCachedEvents(): void;

        _addListener(listener: ((this: MediaQueryList, ev: MediaQueryListEvent) => any)): void;

        _removeListener(listener: ((this: MediaQueryList, ev: MediaQueryListEvent) => any)): void;

        /*** Tracking related methods ***/
        disableTracking(disable: boolean): void;

        isTrackingDisabled(): Promise<boolean>;

        /*** RNBranch singleton methods ***/
        getLatestReferringParams(): Promise<IBranchLinkInfo>;

        getFirstReferringParams(): Promise<IBranchLinkInfo>;

        setIdentity(identity: string): void;

        logout(): void;

        userCompletedAction(event: string, state: any = {}): void;

        getShortUrl(ident: string, linkPropertiesMap: any, controlParamsMap: any): Promise<{ url: string }>;

        sendCommerceEvent(revenue: string, metadata: any): Promise<void>;

        /*** Referral Methods ***/
        redeemRewards(amount: number, bucket: string): Promise<{ changed: boolean }>;

        loadRewards(bucket: string): Promise<{ credits: number }>;

        getCreditHistory(): Promise<any>;

        /*** BranchUniversalObject ***/
        createBranchUniversalObject(identifier: string, options: IBranchUniversalObjectCreationOptions): Promise<IBranchUniversalObject>;
    }

    export {Branch, BranchEvent};
    // noinspection JSUnusedGlobalSymbols
    export default new Branch();
}`

**Comment by kyo504** [comment]
@13thdeus Thanks for sharing! Why don't you open a PR for the file you shared? It would be very helpful for those who search types :)

**Comment by dwilt** [comment]
@13thdeus thanks for putting this in but would love to see this in the base package

**Comment by dwilt** [comment]
@jdee since you guys know the code the best, any chance you guys would be able to do this? Or any plans to move your base code to TypeScript?

**Comment by gran33** [comment]
Come on guys, more than a year passed since this issue opened.
Please, add `typescript` so our infra will be more robust.
🙏

**Comment by pedroraft** [comment]
copypasta module definition, just create a .d.ts and pasta this.

WARNING. this is missing definitions and main class should have more "static" members i think
anyway its a starting point for someone willing to do it, i spent 5 minutes at this
```typescript 
// this is snafu https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/224

declare module 'react-native-branch' {
  interface IBranchUniversalObjectCreationOptions {
    canonicalIdentifier: string;
    title?: string;
    canonicalUrl?: string;
    contentDescription?: string;
    contentImageUrl?: string;
    locallyIndex?: boolean;
    publiclyIndex?: boolean;
    contentIndexingMode?: 'private' | 'public';
    currency?: string;
    price?: string;
    /**
     * format: yyyy-MM-dd'T'HH:mm:ss
     */
    expirationDate?: string;
    keywords?: string[];
    metadata?: any;
    type?: string;
    contentMetadata?: {
      contentSchema?: string;
      quantity?: number;
      price?: number;
      currency?: string;
      sku?: string;
      productName?: string;
      productBrand?: string;
      productCategory?: string;
      productVariant?: string;
      condition?: string;
      ratingAverage?: number;
      ratingCount?: number;
      ratingMax?: number;
      addressStreet?: string;
      addressCity?: string;
      addressRegion?: string;
      addressCountry?: string;
      addressPostalCode?: string;
      latitude?: number;
      longitude?: number;
      imageCaptions?: string;
      customMetadata?: any;
    };
  }

  export interface IBranchLinkInfo {
    $canonical_identifier: string;
    $canonical_url: string;
    $desktop_url: string;
    $exp_date: number;
    $identity_id: string;
    $og_description: string;
    $og_image_url: string;
    $og_title: string;
    $one_time_use: boolean;
    $publicly_indexable: string;
    '+click_timestamp': number;
    '+clicked_branch_link': boolean;
    '+is_first_session': boolean;
    '+match_guaranteed': boolean;
    '~campaign': string;
    '~channel': string;
    '~creation_source': number;
    '~feature': string;
    '~id': string;
    '~referring_link': string;
    '~stage': string;
    '~tags': string[];
  }

  export interface IBranchLinkProperties {
    feature: string;
    channel: string;
  }

  export interface IBranchControlParams {
    $desktop_url?: string;
    $ios_url?: string;
  }

  export interface IBranchShareOptions {
    messageHeader: string;
    messageBody: string;
  }

  export interface IBranchUniversalObject {
    ident: string;
    generateShortUrl: (
      linkProperties: IBranchLinkProperties,
      controlParams: IBranchControlParams,
    ) => Promise<{ url: string }>;
    showShareSheet: (
      shareOptions: IBranchShareOptions,
      linkProperties: IBranchLinkProperties,
      controlParams: IBranchControlParams,
    ) => Promise<{ channel: any; completed: any; error: any }>;
    listOnSpotlight: () => any;
    logEvent: (eventName: string) => any;
    registerView: (ident: string) => Promise<void>;
    release: () => void;
    userCompletedAction: (event: any) => any;
    _newIdent: () => any;
    _tryFunction: (func: any) => any;
  }

  class Branch {
    key: any;
    _checkCachedEvents: boolean;
    _debug: boolean;

    constructor(options: { debug?: boolean });

    static subscribe(
      listener: (params: { error: any; params: any }) => void,
    ): () => void;

    skipCachedEvents(): void;

    _addListener(listener: (this: any, ev: any) => any): void;

    _removeListener(listener: (this: any, ev: any) => any): void;

    /*** Tracking related methods ***/
    disableTracking(disable: boolean): void;

    isTrackingDisabled(): Promise<boolean>;

    /*** RNBranch singleton methods ***/
    getLatestReferringParams(): Promise<IBranchLinkInfo>;

    getFirstReferringParams(): Promise<IBranchLinkInfo>;

    setIdentity(identity: string): void;

    logout(): void;

    userCompletedAction(event: string, state: any): void;

    getShortUrl(
      ident: string,
      linkPropertiesMap: any,
      controlParamsMap: any,
    ): Promise<{ url: string }>;

    sendCommerceEvent(revenue: string, metadata: any): Promise<void>;

    /*** Referral Methods ***/
    redeemRewards(
      amount: number,
      bucket: string,
    ): Promise<{ changed: boolean }>;

    loadRewards(bucket: string): Promise<{ credits: number }>;

    getCreditHistory(): Promise<any>;

    /*** BranchUniversalObject ***/
    createBranchUniversalObject(
      identifier: string,
      options: IBranchUniversalObjectCreationOptions,
    ): Promise<IBranchUniversalObject>;
  }

  export default Branch;
}
```

**Comment by MrAlekhin** [comment]
Any updates on that guys?

**Comment by jbolotin** [comment]
Since this question was initially asked, typescript's popularity has increased by 985%

![image](https://user-images.githubusercontent.com/29549067/88170058-f0d31900-cc14-11ea-9bb4-2d38399481c1.png)

**Comment by ankushShetty1993** [comment]
@pedroraft  After adding react-native-btanch.t.ds file how do I import it and use?

**Comment by RakshithD** [comment]
@pedroraft How can I use the "react-native-branch.d.ts" and How do I import it.!

**Comment by pedroraft** [comment]
@ankushShetty1993 @RakshithD because of the declare module on top of the file everything should work once you paste inside your project, otherwise take a look in to typeRoots configuration on the tsconfig docs

**Comment by bramski** [comment]
3 years old and somebody issued a pull request 4 days ago. Thank you sir! Can we get this merged?
