### ISSUE TITLE
Compilation Error: showShareSheetWithLinkProperties in RNBranch.m does not match method in Branch iOS SDK

### ISSUE THREAD

**Issue by drop-sam** [BranchMetrics/react-native-branch-deep-linking#23]
In RNBranch.m:179, the method
`showShareSheetWithLinkProperties:andShareText:fromViewController:completion:`
does not match the method from the ios-branch-deep-linking repository 
`showShareSheetWithLinkProperties:andShareText:fromViewController:andCallback:`

When attempting to compile this gives the error:
> No visible *@*interface for 'BranchUniversalObject' declares the selector 'showShareSheetWithLinkProperties:andShareText:fromViewController:completion:'

The callback block should also have no return value and accept no parameters because it is only passed to the `UIViewController` instance method `presentViewController:animated:completion`

**Comment by rt2zz** [comment]
just pushed a fix to master, will cut a new npm release after testing. 👍

**Comment by cmmouritsen** [comment]
This is still broken for me in 0.6.1. It looks like your change was reverted in [this](https://github.com/BranchMetrics/react-native-branch-deep-linking/commit/3abe33ce132aa3f94c3db2c713b79a7d194d45e1) commit.

**Comment by rt2zz** [comment]
there was some confusion upstream on what the correct method was. I believe there this may be dependent on the exact branch sdk version you are on. Can you paste you branch version as found in Podfile.lock, e.g. my live project is on
```
  - Branch (0.12.3):
    - Branch/Core (= 0.12.3)
    - Branch/without-IDFA (= 0.12.3)
```

**Comment by cmmouritsen** [comment]
Yeah, I have a different version: 0.11.11
So, I need to update my version of Branch?

**Comment by rt2zz** [comment]
yes that should resolve
