### ISSUE TITLE
In China, the use of WeChat

### ISSUE THREAD

**Issue by chenyanji** [BranchMetrics/react-native-branch-deep-linking#242]
In China, the use of WeChat, because the domain name is not filing and can not jump directly, do you consider this
![image](https://user-images.githubusercontent.com/8857201/29626873-c251c840-8862-11e7-9165-cc4721f712a5.png)

**Comment by jdee** [comment]
If you haven't already, please contact integrations@branch.io or open a ticket in the [Branch support portal](http://support.branch.io/) for help with WeChat issues. I think there may be known problems there. At any rate, this has nothing to do with this SDK.
