### ISSUE TITLE
Android: NoClassDefFoundError / 2.0.0-rc2

### ISSUE THREAD

**Issue by eneskaya** [BranchMetrics/react-native-branch-deep-linking#244]
I am experiencing many crashes in the last time:

```
io.branch.referral.Branch.<clinit> (Branch.java:359)
com.MYAPP.MainApplication.onCreate (MainApplication.java:91)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1013)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:4889)
android.app.ActivityThread.access$1600 (ActivityThread.java:174)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1381)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:146)
android.app.ActivityThread.main (ActivityThread.java:5752)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1291)
```

ReactNative version 0.46.3
Android API Level 19-25
Package version 2.0.0-rc2
 
This is quite a random bug which I cannot yet reproduce.

**Comment by jdee** [comment]
@eneskaya Thanks for the bug report. I'm sorry you're having this problem. You say you cannot reproduce it. How do you know about it? Is there something like a Crashlytics report you could share? Did this happen after an upgrade to the latest version of `react-native-branch`, or is this the first time you've integrated the SDK? (In other words, have you also seen the problem with earlier releases?) It appears that the Branch SDK jar is not being found, but it's not clear why that would happen.

**Comment by eneskaya** [comment]
I see it in Firebase Crash Reporting: 

<img width="1234" alt="bildschirmfoto 2017-08-29 um 09 41 39" src="https://user-images.githubusercontent.com/964419/29810025-9b73e25e-8c9e-11e7-85cd-aa9e66f52491.png">

(It's in German but you'll get the idea 😁)

I'm fairly new to Android, maybe I missed something here. But this seems quite crazy (70 crashes with 22 users)

**Comment by jdee** [comment]
Hi @eneskaya. The 2.0.0 release is out now in NPM. It's probably a good idea to update, but if you can't reproduce the problem, that doesn't tell you much immediately.

Did this start happening after an upgrade to the latest version of react-native-branch, or is this the first time you've integrated the SDK?

Does Firebase give you any more information about the device environment? It's not at all clear why it would not find the Branch jar.

**Comment by eneskaya** [comment]
Actually, what I believe by now is that it may be a general problem in our project. I have seen the same error with other libraries. Will check and report back.

**Comment by eneskaya** [comment]
Ok, I really have no clue what's going on here. And also, I looked into the crash reports more detailed and it's just the Branch SDK which causes the problem:

```
Exception java.lang.NoClassDefFoundError: io.branch.referral.Branch$CUSTOM_REFERRABLE_SETTINGS
```

If anyone has any experience with that I'd be very thankful for advice on how to troubleshoot this problem.

**Comment by sequoiaat** [comment]
@eneskaya Do you still have this issue with latest versions ?

**Comment by VincentRoest** [comment]
I have exactly the same problem problem with running on API 16 (works fine on later API's such as 25, 26). I'm running React Native version 0.53.3 and the branch package 2.3.0.

**Comment by sequoiaat** [comment]
OK. Good to hear that it is working in latest versions.Thanks.

**Comment by newlifehejian** [comment]
this issue still happening on latest branch unity sdk, android 4.4 crash with a NoClassDefFoundError.

**Comment by sbycrosz** [comment]
In case anyone is still looking, this might be relevant https://github.com/BranchMetrics/android-branch-deep-linking/issues/493
