### ISSUE TITLE
Expose CommerceEvent methods

### ISSUE THREAD

**Issue by jasonmerino** [BranchMetrics/react-native-branch-deep-linking#249]
I took a look through the code and was unable to find where the CommerceEvents were exposed to the JS. I'm not super familiar with the Branch SDK, but from what I can tell that part hasn't been bridged over yet.

Are there plans to get that into the React Native SDK or would you be open to a pull request to add that functionality? Because I wouldn't mind helping out on that.

Specifically the method that I'm looking to make use of is the `sendCommerceEvent` method.

**Comment by jdee** [comment]
This was overlooked. It's now in the master branch. 2.0.0 will be released to prod tomorrow. This will be in that release.

**Comment by jasonmerino** [comment]
@jdee Thanks for the super fast turn around on this! That was amazing.
