### ISSUE TITLE
Deep linking redirection stops

### ISSUE THREAD

**Issue by R2V** [BranchMetrics/react-native-branch-deep-linking#269]
I am facing one problem and do not get any clue what the problem. We have implemented Branch SDK for deep linking long back and It is working fine a day before today but when I checked this morning and I clicked any shared link is redirected to Safari and giving pop up "open in App Store" rather than opening My App as My app is installed. We haven't make any change in Frontend as well as Branch dashboard.

**Comment by jdee** [comment]
Hi @R2V. This looks like an instance of a known issue with Universal Links on iOS: https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/110#issuecomment-282893587. Is that consistent with the behavior you see?

**Comment by sequoiaat** [comment]
@R2V  Did the latest version solve this issue for you ?  We tried it and think its no longer an issue in the latest releases. We are marking this as closed . please feel free to reopen it if it still continues to be an issue
