### ISSUE TITLE
'react-native-branch/RNBranch.h' file not found

### ISSUE THREAD

**Issue by blakedallen** [BranchMetrics/react-native-branch-deep-linking#279]
Found an issue when installing via pods, the documentation says to import in AppDelegate.m as such:
``` 
#import <react-native-branch/RNBranch.h>
```

However, this errors and it's not found. I was able to solve this issue by simply importing as such:

```
#import "RNBranch.h"
```

**Comment by blakedallen** [comment]
Actually, will open a pull request.

**Comment by ryanvanderpol** [comment]
@blakedallen did you ever resolve this?  This is also happening in my project.  The discussion in #280 seems to say that this is a result of using a version of React Native < 0.40.0 however I am using 0.48.8, so that is definitely not the problem.

**Comment by otaviosoares** [comment]
I just installed this library for the first time and I have the same issue. I used react-native link though.

React Native 0.55.4

**Comment by NirpE** [comment]
I am using RN 0.55.4 and getting this issue as well. Any solutions how to fix? Changing the import didn't help.

**Comment by joseguerrerov** [comment]
Im using RN 0.57 and Im facing the same issue

**Comment by NirpE** [comment]
For me this comment was helpful to resolve the issue:

https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/361#issuecomment-415149270

**Comment by n13** [comment]
RN60 and latest version of branch
#import <react-native-branch/RNBranch/RNBranch.h>

**Comment by ameernormie** [comment]
working on the app with RN version 0.61 and @n13 solution worked for me.
https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/279#issuecomment-537107307

**Comment by MrAlekhin** [comment]
@blakedallen did you resolve this?
