### ISSUE TITLE
React Native Branch iOS RNBranch.h and Branch.h

### ISSUE THREAD

**Issue by michaelstokes** [BranchMetrics/react-native-branch-deep-linking#284]
Hello, I've recently started working with React Native Branch and its certainly been very helful, was quick to get setup to the most part and Android worked first time round once the params stopped being empty:

    {"+is_first_session":false,"+clicked_branch_link":false,"+non_branch_link":"https://yourapp.app.link/?someparam=123"}

But this was a bit trickier to get around with the iOS version it seemed. 

I was following initially the guide over at https://github.com/BranchMetrics/react-native-branch-deep-linking#setup which was certainly helpful in getting setup, but I seemed to then be facing some issues with the iOS version accepting or even recognizing params passed in. I looked over at the SDK Integration guide for iOS https://dev.branch.io/getting-started/sdk-integration-guide/guide/ios/#recommended-track-in-app-events 

    #import <react-native-branch/RNBranch.h>
    #import "Branch/Branch.h"

I replaced

      if (![RNBranch.branch application:app openURL:url options:options]) {
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
      }
      return YES;

and

    - (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
      return [RNBranch continueUserActivity:userActivity];
    }

with

    // Respond to URI scheme links
    - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
        // pass the url to the handle deep link call
        [[Branch getInstance]
            application:app
                openURL:url
                options:options];
    
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
        return YES;
    }
    
    // Respond to Universal Links
    - (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
        BOOL handledByBranch = [[Branch getInstance] continueUserActivity:userActivity];
    
        return handledByBranch;
    }

from https://dev.branch.io/getting-started/sdk-integration-guide/guide/ios/#recommended-track-in-app-events

and yet keeping 

      [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];

from https://github.com/BranchMetrics/react-native-branch-deep-linking#setup

rather than replacing with 

    Branch *branch = [Branch getInstance];
    [branch initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        if (!error && params) {
            // params are the deep linked params associated with the link that the user clicked -> was re-directed to this app
            // params will be empty if no data found
            // ... insert custom logic here ...
            NSLog(@"params: %@", params.description);
        }
    }];

from https://dev.branch.io/getting-started/sdk-integration-guide/guide/ios/#recommended-track-in-app-events

Although this implementation works, I noticed that initially I reference RNBranch once but later reference just Branch.

The following code from https://dev.branch.io/getting-started/sdk-integration-guide/guide/ios/#recommended-track-in-app-events

    Branch *branch = [Branch getInstance];
    [branch initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        if (!error && params) {
            // params are the deep linked params associated with the link that the user clicked -> was re-directed to this app
            // params will be empty if no data found
            // ... insert custom logic here ...
            NSLog(@"params: %@", params.description);
        }
    }];

Didn't appear to work for me, the subscription from `componentDidMount` was never called and so using 

    [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];

Was called.

I was hoping someone would be able to explain to me what the heck is going on here, I'd rather understand why and how something works, rather than it just working, and also whether there is something wrong with the implementation.

Essentially, I'm just starting out Deep Linking, and wanting to make use of the share feature to then just share links to later be used to pass in params i.e. an id of such thing to route the user to the point in the app.

Thanks very much!

**Comment by jdee** [comment]
The short answer is: If you're using React Native, follow the React Native instructions, not the iOS instructions. Those are for native iOS apps. There are also different instructions with minor differences for Cordova, Titanium, Unity, etc.

If this still isn't working for you, please get in touch with support by opening a ticket at https://support.branch.io or emailing integrations@branch.io, and we'll get your issues sorted out.

Please see also:

- The [official docs](https://docs.branch.io/pages/apps/react-native/)
- Numerous [working examples](https://github.com/BranchMetrics/react-native-branch-deep-linking/tree/master/examples) in the repo
- The [tutorial app](https://github.com/BranchMetrics/react-native-branch-deep-linking/tree/master/examples/webview_tutorial).
