### ISSUE TITLE
[iOS Question] Error from Branch: The network request was invalid.

### ISSUE THREAD

**Issue by wbattel4607** [BranchMetrics/react-native-branch-deep-linking#286]
I've just completed the installation of `react-native-branch` in my React Native project, but I'm having an issue on iOS that I'd like some insight on. I've followed **both** [the setup instructions](https://github.com/BranchMetrics/react-native-branch-deep-linking#ios-setup) **and** [the webview tutorial](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_tutorial/README.md). I have also completed the setup on Branch.io including setting up the Universal Links, URI Schemes, Bundle Identifiers, etc....

#### AppDelegate.m
```
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

...

#import <react-native-branch/RNBranch.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    ...

    // Uncomment this line to use the test key instead of the live one.
    // [RNBranch useTestInstance];
    [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];

    ...
}

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    BOOL handled = YES;
    if (![RNBranch.branch application:app openURL:url options:options]) {
        handled = [[FBSDKApplicationDelegate sharedInstance] application:app openURL:url sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey] annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];
    }
    return handled;
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
    return [RNBranch continueUserActivity:userActivity];
}

...
```

#### Info.plist (sensitive info censored)
<img width="854" alt="screen shot 2017-11-13 at 12 03 03 am" src="https://user-images.githubusercontent.com/13490339/32710540-fab2016c-c806-11e7-826f-64346e4ae6da.png">

The Associated Domains Capability has been properly setup, and the` foobar.entitlements` file (which I confirmed does have the correct applinks) has been added to the Copy Bundle Resources build phase.

#### App.js
```
...

import Branch from 'react-native-branch';

class App extends Component {

    constructor() {
        super();
        this.state = {...};

        ...

        this._unsubscribeFromBranch = null;
    }

    ...

    componentDidMount() {

        ...

        this._unsubscribeFromBranch = Branch.subscribe(({ error, params }) => {
            if (error) {
                console.error('Error from Branch: ' + error); // <- Error comes from here (App.js:118)
                return;
            }

            // params will never be null if error is null
            console.log('Branch params: ' + JSON.stringify(params));

            if (params['+non_branch_link']) {
                const nonBranchUrl = params['+non_branch_link'];
                console.log('non-Branch link URL: ' + nonBranchUrl);
                // Route non-Branch URL if appropriate.
                return;
            }

            if (!params['+clicked_branch_link'])
                return;

            // Get title and url for route
            let title = params.$og_title;
            let url = params.$canonical_url;
            let image = params.$og_image_url;

            // Now push the view for this URL
            this.navigator.push({ title: title, url: url, image: image });
        });
    }

    componentWillUnmount() {

        ...

        if (this._unsubscribeFromBranch) {
            this._unsubscribeFromBranch();
            this._unsubscribeFromBranch = null;
        }
    }

    ...
}
```

### Environment
- `react-native-branch: 2.1.1`
- `react-native-fbsdk: 0.6.3`
- `react-native: 0.50.3`
- `react: 16.0.0`
- Tested on:
  - iOS 11.1 Simulator (got error)
  - iOS 11.1 Physical Device (got error)
  - iOS 10.3.1 Simulator (got error)
  - Android 7.1.1 API Level 25 Emulator (did not get error)
- Built on macOS Sierra
- Built with Xcode 9 and Android Studio 3

**This error happens when I build the React Native project, not even trying to use a link of any kind.**

This isn't fatal, and I can dismiss it to continue on using the app, but I'd still like to figure out why it is throwing the error.

This is only happening on iOS. I'm not getting any errors on Android.

Let me know if this is more appropriate for the Branch support team- but I wanted to ask here first.

Thanks! :)

![image uploaded from ios 4](https://user-images.githubusercontent.com/13490339/32710114-bea86510-c803-11e7-9e25-b7bf8f8f44a5.png)

**Comment by wbattel4607** [comment]
Going back through everything, it seems that I neglected to insert the proper keys into `branch.json`.

After doing this it seems the problem is gone. I'm closing this on the assumption that it is working now, and I'll reopen it if the problem returns.

Thanks!

**Comment by witalobenicio** [comment]
@wbattel4607 did you had to unlink and link again to make it work?

**Comment by wbattel4607** [comment]
@witalobenicio it was a while ago so I don't remember exactly, but I definitely was relinking many times for different reasons so that very well may have been part of it, but I'm not sure. The original problem was that I didn't have the project API keys in the branch.json file.

**Comment by octobus55** [comment]
I was having the same issue and found out that there was a problem with accessing the keys in my environment files with react-native-config. If you are having this problem just enableLogging and check your logs, the logs are more detailed so it's easier to detect the main problem
