### ISSUE TITLE
Not opening the app

### ISSUE THREAD

**Issue by bacancy-swaroopa** [BranchMetrics/react-native-branch-deep-linking#288]
Hi I used this module 
And when I click on Link It always takes me tot eh url that I has given in the branch dashboard and not to the app (App is already there) in iOS simulator

Here I am attaching the screenshots of my branch dashboard and the info.plist 
Can anyone tell me where is the exact issue:

![screen shot 2017-11-22 at 12 44 34 pm](https://user-images.githubusercontent.com/31623477/33114516-30f67144-cf83-11e7-894b-eafe7539a8d7.png)
![screen shot 2017-11-22 at 12 45 04 pm](https://user-images.githubusercontent.com/31623477/33114520-35d471fc-cf83-11e7-803e-8a2c2873bc9c.png)
![screen shot 2017-11-22 at 12 45 12 pm](https://user-images.githubusercontent.com/31623477/33114523-383932e8-cf83-11e7-9167-6def5376b8f0.png)
![screen shot 2017-11-22 at 12 45 27 pm](https://user-images.githubusercontent.com/31623477/33114526-394dc5f4-cf83-11e7-807b-8f785eaa0f68.png)

Please help me ASAP 
Thanks

**Comment by sequoiaat** [comment]
Hi

We replicated the issue and we found that you  didn’t give “applinks:’’ tag before the link domain in the associated domain part. If you do that the problem gets fixed. 

thanks
