### ISSUE TITLE
xcode library not found for -lBranch-SDK

### ISSUE THREAD

**Issue by adirzoari** [BranchMetrics/react-native-branch-deep-linking#289]
i have react native v0.49. After installing react-native-branch I try to run with xcode and I get the error

> ld: library not found for -lBranch-SDK
in addition,when I run react-native-link I get

> react-native-branch ERR! Failed to add file to project

**Comment by perrosnk** [comment]
+1

**Comment by kollner** [comment]
+1

**Comment by sequoiaat** [comment]
Is this still an issue after upgrading to the latest version of RN library ?   If you are still on RN 0.49 , can you please check if all  the modules are installed and path defined correctly as we were not able to replicate the issue at our end.

**Comment by sequoiaat** [comment]
Hope this is ok now. We are closing it, please re-open if you are facing any issue.
