### ISSUE TITLE
No way to add transactionID with react-native-branch@2.1.1

### ISSUE THREAD

**Issue by jasonmerino** [BranchMetrics/react-native-branch-deep-linking#297]
I am running version 2.1.1 of this SDK and am looking to send `transactionID` along with my `sendCommerceEvent` call. I'm not seeing any documentation (event in the newest version of the SDK - 2.1.1) which shows that this is possible and I have tried adding it to the metadata parameter of the `sendCommerceEvent` call and it doesn't come through as a transaction ID.

It looks like there has been some work in master to be able to send a transaction ID but with the current SDK version. So this is technically part issue with the SDK, part question on when this feature will be released.

Thanks!

**Comment by jdee** [comment]
The `sendCommerceEvent` method is deprecated in 2.2.0, which is in the master branch. Here's the new API: https://github.com/BranchMetrics/react-native-branch-deep-linking#tracking-user-actions-and-events.

Do something like:

```js
import { BranchEvent } from 'react-native-branch'

const event = new BranchEvent(BranchEvent.Purchase, buo, { transactionID: 'abc', price: 20.00 }).logEvent()
```

Or on a single BUO:

```js
buo.logEvent(BranchEvent.Purchase, { transactionID: 'abc', price: 20.00 })
```

This will be released soon, probably by the end of the week. What's in the master branch is pretty solid, and you should be able to work with it. You'll see some native deprecation warnings. There is also a new API for the Branch Universal Object that will be part of this release. That should be in the master branch by tomorrow.

**Comment by jasonmerino** [comment]
Great, thanks @jdee. I eagerly await its release. :)

**Comment by jasonmerino** [comment]
Hey @jdee, I don't mean to be a pain, but do you have a new estimate when this may be released. Thanks!

**Comment by jdee** [comment]
2.2.0 has been released with the support you need. Please let us know if you have any further issues.
