### ISSUE TITLE
unexpected '@' in program - iOS

### ISSUE THREAD

**Issue by atlanteh** [BranchMetrics/react-native-branch-deep-linking#308]
When building the app I get the following error:  

```
    ✗ node_modules/react-native-branch/ios/RNBranch.m:[221,9] unexpected '@' in program
    »     if (@available(iOS 8.0, *)) {
    »         ^
    ▸ Compiling NSString+Branch.m
    ** ARCHIVE FAILED **
    The following build commands failed:
    	CompileC /tmp/sandbox/5910ebcbb834550001903d79/bbbuild/Build/Intermediates/ArchiveIntermediates/MyApp\ -\ Development/IntermediateBuildFilesPath/RNBranch.build/Release-iphoneos/RNBranch.build/Objects-normal/armv7/RNBranch.o RNBranch.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

How do I solve this?

**Comment by jdee** [comment]
Could you please do the following?

```
[sudo] gem install branch_io_cli
cd /path/to/project
br report -H
```

That generates some useful information about project configuration and environment, so I don't have to ask a ton of questions. Though I do have two more questions that the CLI report will not (yet) include:

1. Version of React Native
2. Version of react-native-branch

Can you please send that output and the answers to those questions to `integrations@branch.io`? That will open a private support ticket, and we can help you get the problem resolved quickly. Thanks.

**Comment by jdee** [comment]
@atlanteh I got a different error in the same place building with Xcode 8. That change was introduced by Xcode 9 for Xcode 9, which was generating a warning there. But removing the unnecessary check for iOS 8 no longer produces a warning with Xcode 9.2, so I've removed it altogether in the master branch. I'll get that released today. If you have further trouble building, please contact support, and we'll make sure you get the help you need.

**Comment by atlanteh** [comment]
Awesome! The failing build is in BuddyBuild so I can't actually access it. I saw u released a new version that should fix the error. Can you please publish to npm as well?
Thx!

**Comment by jdee** [comment]
It was published. 2.2.2 has the fix.

**Comment by atlanteh** [comment]
Ahh I saw 2.2.3 in package.json.
The new release solves the issue. Thx!
