### ISSUE TITLE
Can't compile project on iOS : Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by mlumbroso** [BranchMetrics/react-native-branch-deep-linking#31]
Hi,
using 0.4.0
This is the errors I got :
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Branch", referenced from:
      objc-class-ref in libRNBranch.a(RNBranch.o)
  "_OBJC_CLASS_$_BranchLinkProperties", referenced from:
      objc-class-ref in libRNBranch.a(RNBranch.o)
  "_OBJC_CLASS_$_BranchUniversalObject", referenced from:
      objc-class-ref in libRNBranch.a(RNBranch.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks for your help

**Comment by mlumbroso** [comment]
Apparently including libBranch.a manually did the trick

**Comment by alfonsodev** [comment]
I have the same problem but adding manually libBranch, doesn't fix it

**Comment by jdee** [comment]
Hi @alfonsodev. Sorry for the delay in getting back to you. Can you provide some information on what versions you're using, particularly react-native-branch and react-native? Are you just getting started with react-native-branch, or did this occur when you upgraded? Thanks.

**Comment by mikhapy** [comment]
incluiding libreact-native-branch.a manually in Build Phases -> Link Binary with libraries fix the problem.
