### ISSUE TITLE
Different payload for Android and iOS

### ISSUE THREAD

**Issue by wprater** [BranchMetrics/react-native-branch-deep-linking#311]
When I share a link with share widget, and add `contentMetadata.customMetadata`, Android places the data on the root level and iOS puts it in the `params.$custom_fields`.  Why is this behavior inconsistent?

**Comment by wprater** [comment]
Meanwhile, I decided to set the needed data in the control params, as they always seem to be placed on the root of the params.

**Comment by jdee** [comment]
This is being addressed in the native SDKs. There will be a new release of this SDK soon, once both platforms are released.

**Comment by jdee** [comment]
This has been fixed in iOS SDK 0.22.4, which is available in release 2.2.3 of this SDK in NPM.

**Comment by wprater** [comment]
thanks, so it looks like iOS will behave like Android and remove the `$custom_fields` prop? 

https://github.com/BranchMetrics/ios-branch-deep-linking/pull/771/files

**Comment by wprater** [comment]
would you say it's preferred to use the `contentMetadata.customMetadata` over `controlParms` as I was to work around the issue?

**Comment by jdee** [comment]
Yes to both questions. For one thing, control params are per link. I'm not sure if it's intended to add custom control params. customMetadata are per content item, and that's what the field is there for.

But honestly this is getting beyond what I actually know. If you contact `integrations@branch.io` or open a support ticket at `https://support.branch.io`, you'll probably get better answers.
