### ISSUE TITLE
[android] branch.subscribe fired only when app is closed

### ISSUE THREAD

**Issue by EugeneDraitsev** [BranchMetrics/react-native-branch-deep-linking#312]
Hi, i trying to handle branch events in my root level component like that:

```
componentDidMount() {
  branch.subscribe(({ error, params }) => {
    console.log(params)
    if (error) {
      console.log('Error from Branch'  + error)
    }
  })
}
```

I get an event, but only when app is closed (during first app launch). When app is open and i trying to visit some url or send deeplink by adb - nothing happens.
Also if I add to componentDidMount this handler: 
```
Linking.addEventListener('url', ({ url }) => {
  console.log(url)
})
```
I able to see urls, but ` branch.subscribe` still doesn't log anything. 
Can you help me with it? Probably I missed something

**Comment by jdee** [comment]
Thanks for reporting this. This sounds like an instance of a known issue in the native Android SDK that has been reported elsewhere. I have so far not been able to reproduce it with RN. But there is a fix in the Android SDK that should be released early next week. Once that happens, we'll do another release of this SDK.

**Comment by jdee** [comment]
Release 2.2.4 is available in NPM with Android SDK 2.14.4. If you have any further trouble, please get in touch with integrations@branch.io.

**Comment by edraitsev** [comment]
Seems like it's still not fixed.

How to reproduce: 
Just run `adb shell am start -W -a android.intent.action.VIEW -d "mychat://mychat/chat/Taylor" com.simpleapp`. More details [here](https://reactnavigation.org/docs/guides/linking#Android)

I get event in `branch.subscribe` **only** if app is killed. On ios all works as expected, so this is android issue.

**Comment by dwaligora** [comment]
Hi @EugeneDraitsev were you able to fix your issue? I am encountering probably the same one: https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/322.

**Comment by NirpE** [comment]
Also seeing this issue with ^4.2.1
