### ISSUE TITLE
Integer control param on Android causes invalid OpenGraph property

### ISSUE THREAD

**Issue by leethree** [BranchMetrics/react-native-branch-deep-linking#314]
In JavaScript, call `showShareSheet` with the following control params:
```js
{
  $og_image_height: 400,
  $og_image_width: 400,
  $og_image_url: "<redacted>",
  // and other properties ...
}
```

On Android, number `400` will be converted to `400.0` in the `meta` tags when Facebook scrapes the link:

<img width="515" alt="sharing_debugger_-_facebook_for_developers" src="https://user-images.githubusercontent.com/648142/35093689-09184800-fc7e-11e7-9222-2ebc28b23d8a.png">

(Screenshot from [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/))

"400.0" is invalid OpenGraph tag and it will cause problems such as missing App Links information.

This bug doesn't occur on iOS.

**Comment by leethree** [comment]
Also `null` values will result in `"Null"` strings.

**Comment by sequoiaat** [comment]
Hello,

This has been fixed. It will be deployed soon.

Thanks
