### ISSUE TITLE
Please write deprecations and breaking changes on Releases

### ISSUE THREAD

**Issue by brunolemos** [BranchMetrics/react-native-branch-deep-linking#315]
Just spent some time investigating why my metadata wasn't working.
I found out the field changed by looking at blame information in the code, because I didn't see anything related to it on the release notes.

Please write deprecations and breaking changes there, it will help a lot on future migrations 🙌

**Comment by sequoiaat** [comment]
We will try to ensure that we take care of this request in future releases
