### ISSUE TITLE
Custom events on android platform crash the app enum error

### ISSUE THREAD

**Issue by mieszko4** [BranchMetrics/react-native-branch-deep-linking#317]
While implementing referral mechanism I tried to add a custom event on which reward would be triggered.
I do the following:
```es6
import Branch, { BranchEvent } from "react-native-branch";

const event = new BranchEvent("customevent");
event.logEvent();
```

But the app crashes on `logEvent()` call with:
```
No enum constant io.branch.referral.util.BRANCH_STANDARD_EVENT.customevent
valueOf
    Enum.java:254
valueOf
    BRANCH_STANDARD_EVENT.java:9
createBranchEvent
    RNBranchModule.java:526
logEvent
    RNBranchModule.java:336
invoke
    Method.java
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:761
```

**Comment by john1jan** [comment]
i am also getting the same issue
![screenshot_1517998901](https://user-images.githubusercontent.com/4264813/35911097-cfe96b9e-0c1e-11e8-865d-5f7a0d584eb7.png)

**Comment by john1jan** [comment]
any update on this?

**Comment by Genitivo** [comment]
news about this?? I'm stuck up with the same error

**Comment by sequoiaat** [comment]
We have a fix for this and will get published in soon.

**Comment by sequoiaat** [comment]
Fix has been published

**Comment by nkov** [comment]
@sequoiaat Experiencing this off a fresh install from npm. The latest is 2.2.4 but in github I see 2.2.5, is this the fix? Will you publish it to npm?

**Comment by sbycrosz** [comment]
+1 for publishing this to npm. This is kind of a blocker for us to start sending events to branch 🙁
