### ISSUE TITLE
VERSION wrong in console.log

### ISSUE THREAD

**Issue by mieszko4** [BranchMetrics/react-native-branch-deep-linking#318]
Please update `VERSION` at https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/src/index.js#L9

I am using v.2.2.4 and I see `Initializing react-native-branch v. 2.2.2` - it is confusing

**Comment by sequoiaat** [comment]
Thanks for pointing t out.  We will fix this and merge
