### ISSUE TITLE
IOS unable to get params

### ISSUE THREAD

**Issue by xcrafter** [BranchMetrics/react-native-branch-deep-linking#325]
I am not receiving params in ios. The only thing i am getting is "+non_branch_link" param, i am not getting the extra data passed with that deep linking url. Android it works fine

I am using branch 2.2.4
React native : 0.48

**Comment by blastering66** [comment]
Yea me too... it works before....

im using 
"react-native": "0.47.2",
"react-native-branch": "^2.1.1"

**Comment by sequoiaat** [comment]
We are trying to look into this to find a solution  for this. will update soon

**Comment by gmeluski** [comment]
Just here to say I am experiencing a similar issue on react-native 0.52.2:

A specific link is not passing in data to the callback of `branch.subscribe`. This was working previously, however it now fails to work across different versions of the library (`2.2.4`, `2.1.1`, & `2.0.0` all on iOS), which makes me think something may be wrong with the link itself. I have other links that were generated more recently which pass in the full set of data as expected.

(FWIW I also filed a general support ticket with Branch, just covering all the possible outlets I can here)

The deeplink does LAUNCH the app as expected - I tested it from the iOS Gmail client and from the native Messages app, both with the same result of no additional data coming in for that specific link.

Here's what the data object looks like when it comes through sans data:


```
{
  "error": null,
  "params": {
    "+clicked_branch_link": false,
    "+is_first_session": false
  },
  "uri": null
}
```

**Comment by njculpin** [comment]
@gmeluski - same with react-native-cli: 2.0.1, react-native: 0.50.4, branch 2.1.1...tested on ios. The link only shows up as a non-branch link. Manually creating the link in the branch dashboard seems to work though.

does anyone have an idea on how to manually unwrap the link?

**Comment by sequoiaat** [comment]
Hello,
Did you tried it in latest version? Can you send me the non branch link with parameters which you are trying to pass?

**Comment by njculpin** [comment]
my links are generated via curl https://docs.branch.io/pages/apps/api/#link, is this not supported?

**Comment by sequoiaat** [comment]
It should work. let us look into and revert back in few hours

**Comment by njculpin** [comment]
this is the command we are using:

`curl -XPOST https://api.branch.io/v1/url \
  -d '{
  "branch_key": "key_test_",
  "channel": "email",
  "campaign": "email",
  "data": {
    "token": "token",
    "email": "test@test.com",
    "app_action": "reset_password"
  }
}'`

**Comment by blastering66** [comment]
Here is my result from branchio
no param at all.

![screen shot 2018-05-04 at 1 46 35 pm](https://user-images.githubusercontent.com/3015184/39615647-9a712648-4fa1-11e8-895a-fb8cfeefc0c6.png)

Here is my code, i put on AppNavigator 

![screen-shot-2018-05-04-at-1 40 05-pm](https://user-images.githubusercontent.com/3015184/39615636-8a58c57c-4fa1-11e8-8a9d-ccaaeece945a.jpg)

**Comment by sequoiaat** [comment]
@njculpin 

Can you try to give the token as custom object and see if it works . Please see to the attached code snippet below - 


curl -XPOST https://api.branch.io/v1/url \
  -d '{
  "branch_key": "enter your branch key here",
  "channel": "facebook",
  "data": {
    "$canonical_identifier": "content/123",
    "$og_title": "Title from Deep Link",
    "$og_description": "Description from Deep Link",
    "custom_boolean": true,
    "custom_integer": 1243,
    "custom_string": "everything",
    "custom_array": [1,2,3,4,5,6],
    "custom_object": {
    "token": "token",
    "email": "test@test.com",
    "app_action": "reset_password"
    }
  }
}
 
Please refer to  - https://docs.branch.io/pages/apps/api/#link

**Comment by njculpin** [comment]
@sequoiaat - Copied your exact curl.
So it seems that its an issue with Test Versus Live Keys...I can get around that.
Test Key - Fails for both Android & iOS. Returns the same non-branch object that @blastering66 posted on both platforms.
Live Key - Passes.

thank for you help!

**Comment by blastering66** [comment]
@sequoiaat i dont think its typo.. cuz on android it works. it work before in iOS but after a few updates on this repo release, it wont work anymore.

i already update the version to the current release, but still not get the params on ios device & ios emulator

**Comment by Boris-Vladimirovich** [comment]
The same issue. Android works fine, but on ios got this:
'Subscribe params', { '+non_branch_link': 'https://XXXXXX.app.link/XXXXXXX',
  '+is_first_session': false,
  '+clicked_branch_link': false }
Link is correct. Can you give any advices how to find a reason?

**Comment by Boris-Vladimirovich** [comment]
I`ve found solution. In my case I changed `useTestInstance` to `false` in `myProject/branch.json`. Hope it`s helpful for somebody.

**Comment by tstrand** [comment]
Yup, same for me. I was using the live instance with test links

**Comment by sequoiaat** [comment]
We are closing it, please re-open if you are facing any issue.
Also passing sensitive keys like "Token" are blocked, and won't return deep link data (we don't want to be liable to store PII).

**Comment by witalobenicio** [comment]
For me the solution doesn't work. I've set to false, and still not getting data.

**Comment by witalobenicio** [comment]
The problem was that I didn't create the branch.debug.json. Now it's ok.

**Comment by priyak-sdei** [comment]
But i am still facing the same issue

**Comment by OshithaIdeaBits** [comment]
this issue is happen 5.9.0 SDK version also. In Android customMetadata is coming. But iOS  customMetadata not coming 

in here params not get customMetadata in iOS , but Android working fine. 
```
branch.subscribe({
onOpenComplete: ({
        error,
        params,
        uri
      }) => {
}
})
```
