### ISSUE TITLE
Branch.openURL() does not work on android

### ISSUE THREAD

**Issue by mieszko4** [BranchMetrics/react-native-branch-deep-linking#328]
About 2 months ago we integrated branch into our react-native app and after some struggling I managed to make it all work.

However, recently on android branch links stopped working for us (we've upgraded to the newest version), so  I've followed the instructions of integrating branch again and managed to make it work except for programmatic `Branch.openURL()`

At first we had struggles to recognize branch links at all (after following https://github.com/BranchMetrics/react-native-branch-deep-linking#programmatic-deep-linking and changing `onStart` to `onResume`). The following code, however, made it work:

```java
@Override
    protected void onResume() {
        super.onResume();

        Intent currentIntent = getIntent();
        Uri uri = currentIntent.getData();

        // force branch to init session
        if (uri != null) {
          currentIntent.putExtra("branch", uri.toString());
          currentIntent.putExtra("branch_force_new_session", true);
        }

        RNBranchModule.initSession(currentIntent.getData(), this);
    }
```

_I am actually not sure if that's how it is supposed to be done..._

### The main issue here
Anyway, for some reason when triggering `Branch.openURL()` branch does not recognize the link as branch link - in the log I see:
```
{ params: { '+is_first_session': false, '+clicked_branch_link': false }
```

It is even more interesting that it does recognize when I call it while the app is loading.

**Comment by sequoiaat** [comment]
Hello,
Are you trying to open the deep link of your App inside your app itself ? Please clarify.

**Comment by mieszko4** [comment]
Yes, when I run `Branch.openURL(myAppDeepLink)` within my app nothing happens on android - branch link is not recognized.

**Comment by Fefbug** [comment]
Hi, 
same issue for me. 
I had to use the branch android sdk 2.15.0 to fix it

upgraded by this commit : https://github.com/BranchMetrics/react-native-branch-deep-linking/commit/035cec6cb4fa155f65672c3f715eac991e0488d1

**Comment by sequoiaat** [comment]
@mieszko4  - Did upgrading  solve your issue  ?

**Comment by mieszko4** [comment]
Yes, upgrading android branch sdk to 2.15.0 makes it work again! (I actually checked with latest master, i.e. https://github.com/BranchMetrics/react-native-branch-deep-linking/commit/472c6111fa2156f69d8cc57c92d3d0bf96fb8bc6)

I've actually encountered some problems when building:
```
Could not list contents of '/node_modules/react-native-branch/examples/testbed_native_ios/Pods/Headers/Public/Yoga/YGNodeList.h'. Couldn't follow symbolic link.
```
After removing some folders like this one it built fine.

When could we expect a release in npm?

**Comment by sequoiaat** [comment]
Latest version 2.2.5 has been released, Please use it.

Thanks

**Comment by radekcy** [comment]
Hi, I have a similar issue with v4.4.0. When I try to use branch.openURL(branchLink) to open a link within my app nothing happens on Android. Downgrading to v4.2.1 seems to solve the issue.

**Comment by Cirych** [comment]
"react-native-branch": "^5.0.0-beta.1", same.

**Comment by odital** [comment]
> "react-native-branch": "^5.0.0-beta.1", same.

Same case here.

**Comment by johnhaup** [comment]
Same on 5.0.4
