### ISSUE TITLE
Show referrer in Branch.getCreditHistory

### ISSUE THREAD

**Issue by mieszko4** [BranchMetrics/react-native-branch-deep-linking#329]
I make a request for history using `Branch.getCreditHistory`.

if I am a referrer I can see both `referree` and `referrer` which is great.

However, when I am a referree I do not see `referrer`.
Is that on purpose? Is there a setting to make the `referrer` visible in the credit history?

**Comment by sequoiaat** [comment]
Hello,
Yes, This feature is not supported by default. But you can enable it by creating new reward rules in Referrals. Referral programs documentation:  https://docs.branch.io/pages/viral/referrals/ 

Thanks

**Comment by sequoiaat** [comment]
OK, Please see the specifc section for adding rules in link - https://docs.branch.io/pages/viral/referrals/#rule-1-rewarding-the-referred-user-10-credits . Hope it helps.

Thanks

**Comment by mieszko4** [comment]
Thanx for your input.
I already had this rule set up.
The issue is not that users do not get credits - both referrals and referees get their credits.
The issue is that in my app I want to list my referrer but the field is `undefined` instead of referrer's email.
