### ISSUE TITLE
Swift imports regression

### ISSUE THREAD

**Issue by guysegal** [BranchMetrics/react-native-branch-deep-linking#33]
Hi,
I noticed that in version 0.4.0 there was a regression in the swift import fix.
The fix that was added in commit 'a97f7a06b033673c1df1ec7bb0804db91acabf1c'

**Comment by rt2zz** [comment]
In react-native 0.30 the `<React/*.h>` style of importing no longer works.

Can you explain why swift requires that style of import? If you have a chance can you play around with the project and see if you can get it to build? I will happily accept a PR that fixes the issue and maintains 0.30 compatibility.

**Comment by guysegal** [comment]
We'll upgrade our project to RN 0.30 soon and I'll check it

**Comment by guysegal** [comment]
However if this is related to RN 0.30 I think you need to change the dependency version in packages.json

**Comment by rt2zz** [comment]
Ok after digging a little deeper:
- rn 0.30 no longer supports the `#import <React/*.h>` import syntax
- it may (?) be possible to change the build settings of react-native-branch to bring back support, PR's welcome
- in the mean time I released `v0.5.0-swift` using the swift compatible import `npm i --save react-native-branch@swift`
- unrelated, I rolled back the event emitter update as this was causing issues for people on rn < 0.28

Hope that helps. Let me know if anything else is needed for swift compatibility. I will keep an eye on restoring support to the main release.

**Comment by rt2zz** [comment]
@guysegal if you have a chance can you give this a go using the latest react-native-branch on RN 0.30+.

**Comment by guysegal** [comment]
I'll check it soon and post the result. Thanks!

**Comment by aaustin** [comment]
Closing issue until further update.
