### ISSUE TITLE
Android: Crash upon app start

### ISSUE THREAD

**Issue by a-koka** [BranchMetrics/react-native-branch-deep-linking#335]
Looks like the following change to `AndroidManifest.xml` causes the app to crash upon load. Everything else in the `react-native` integration documentation seems to work fine.

`android:name="com.eneff.branchandroid.CustomApplicationClass"`

Anybody else having the same issue?

**Comment by sequoiaat** [comment]
Hello,
It may be due to the wrong configuration of the android:name. You have to provide the main class path. Removing it or providing the wrong Class can be the reason for the crash. 
Can you please send us the exact value you have given for the android:name ?

**Comment by a-koka** [comment]
Thanks for the response @sequoiaat. The documentation needs to be updated as it suggests to make this change. My problem is resolved after using my application name.

Should we leave this ticket open to address the documentation?

**Comment by sequoiaat** [comment]
We are updating the documentation. we will close this currently

**Comment by akbokha** [comment]
Is the documentation up to date as of now? In particular,
Should one set `android:name="com.eneff.appname.CustomApplicationClass"` (on <application.. level)? (where appname needs to be filled in).

Apart from this, other elements of the documentation should be updated anyway (e.g. the link behing "Register for Google Play Install Referrer." is outdated)

**Comment by obiwankenoobi** [comment]
Still having hard time to understand the docs, should it be:  

`android:name="com.eneff.{appName}.CustomApplicationClass"`

or should it be:

`android:name=".MainApplication"` as it was before integrating Branch?

**Comment by mllrmat** [comment]
Would be great if this could be changed in the documentation as it is not clear what needs to be done. If there is no need for a changing the android:name=".MainApplication", do not mark it!

**Comment by obiwankenoobi** [comment]
@mllrmat yes it can be really annoying. Anyway I did leave it  `android:name=".MainApplication` and it works so you should try it.

**Comment by MoeMamdouh** [comment]
Hi, 
i still have this crash issue, and the solution not clear for me
should i  leave it 
`android:name=".MainApplication` or should i update it?
@a-koka  @sequoiaat  @obiwankenoobi

**Comment by obiwankenoobi** [comment]
@MoeMamdouh leave it as is.
