### ISSUE TITLE
Always getting example Apple Search Ads campaign as referring params

### ISSUE THREAD

**Issue by wbattel4607** [BranchMetrics/react-native-branch-deep-linking#338]
After clicking on a branch link generated and shared from another user from a BUO...

```
this._unsubscribeFromBranch = Branch.subscribe(({ error, params }) => {
    if (error) {
        console.error('Error from Branch: ' + error);
        return;
    }

    // params will never be null if error is null
    console.log('Branch params: ' + JSON.stringify(params));
});
```
↑ this gives me this ↓
```
Branch params: {"+clicked_branch_link":false,"+is_first_session":true}
```
and then...
```
const firstParams = await Branch.getFirstReferringParams();
console.log(firstParams);
```
↑ this gives me this ↓
```
$3p: "a_apple"
~ad_set_id: 1234567890
~ad_set_name: "AdGroupName"
~advertising_partner_name: "Apple Search Ads"
~branch_ad_format: "App Only"
~campaign: "CampaignName"
~campaign_id: 1234567890
~channel: "Apple App Store"
~creative_name: "CreativeName"
~feature: "paid advertising"
~tags: ["Keyword", "LineName"]
```
even though both branch.json and branch.debug.json include
```
"appleSearchAdsDebugMode": false
```
and my AppDelegate.m does NOT include `[[Branch getInstance] setAppleSearchAdsDebugMode]`

Any idea why this happens? I'm trying to get the data about who referred this user but all I get is this dummy search ad example.

### Environment:
- macOS High Sierra
- Xcode 9.2
- iOS 11.2.X
- "react-native": "0.54.2" (also tested on 0.53.3)
- "react-native-branch": "~2.2.4"
- Branch-SDK (0.22.4)

**Comment by sequoiaat** [comment]
Hi

We think this is similar to  issue 282 and a fix is on its way

thanks

**Comment by wildseansy** [comment]
This seems pretty bad. We think this issue is also messing up our authentic referrals to the app, which have huge repercussions on that user flow. Please release a fix soon -- this seems like one of the most core pieces of branch's functionality.
