### ISSUE TITLE
subscribe method called twice

### ISSUE THREAD

**Issue by lprhodes** [BranchMetrics/react-native-branch-deep-linking#34]
Hi,

TheBranch.subscribe callback is being called twice when opening an old-style URI deep link.

The `[[Branch getInstance] handleDeepLink:url];` code within the `handleDeepLink:` method is returning as false however `Branch.subscribe` is still being called.

Then when `[[NSNotificationCenter defaultCenter] postNotificationName:initSessionWithLaunchOptionsFinishedEventName object:nonBranchResult];` is called, the `Branch.subscribe` method is called again.

Commenting the postNotification out fixes the issue for me.

Any ideas?

Thanks

Luke

**Comment by rt2zz** [comment]
@lprhodes apologize for letting this drop off my radar. You solution is correct, I have implemented it on a [separate branch](https://github.com/BranchMetrics/react-native-branch-deep-linking/tree/non-branch) for now, will include with next release.

Thanks!

**Comment by rt2zz** [comment]
👍  released
