### ISSUE TITLE
link's query params as blank in branch.subscribe() method when deep linking with sendGrid email service provider 

### ISSUE THREAD

**Issue by Jaydipsinhv** [BranchMetrics/react-native-branch-deep-linking#347]
## Goal
I am sending email with deep linking implementation with Branch.IO with sendGrid integration. While user click on link my react native app open in phone and redirect me to screen based on query params in url which i have provided during create link in API.

## Problem

I am able to open app from link but query params i have provide in link is display as blank. so i am not able to open screen where i want to redirect to user in app.

```
branch.subscribe(({ params, error, uri }) => {
  if (error) {
    console.log('Error from Branch: ' + error)
    return
  }
  console.log("params :: ", params);
  if(params.reset) {
    // Redirect user to reset password screen
    console.log("params.reset :: " + params.reset);
    Actions.resetpassword({resetToken: params.reset});
  } else if(params.verify) {
    // Verify signup user
    axios.post('http://localhost:3030/authmanagement', {
        "action":"verifySignupLong",
        "value": params.verify
      }).then(response => {
          Actions.login({isVerifySuccess: true});
      }, error => {
        Actions.login();
      });
  }
});
```

I have write this code as suggest Branch.IO documentation. In params i have send reset and verify token which i got as blank string.

## Additional Information

This code is working without integration with sendGrid in deep linking. But for mailing tracking i used sendGrid. So when i try to email with sendGrid it will create problem.

I have setup Link Branding in SendGrid account and also add CNAME in my domain as given in instruction of sendGrid integration for deep linking.

I have check mailed link in Redirect Detective portal

I have verified link and it will generate valid url with params. please look into below image for more clarification

![redirectdetective](https://user-images.githubusercontent.com/37183780/40167174-f142657c-59dd-11e8-877e-0c4ed37182c8.png)

**Comment by sequoiaat** [comment]
@Jaydipsinhv 
It seems that the branch link you are  passing is not valid,
For e.g., valid url seems to be like: https://example.app.link/**AAG0ALLzmH**?token=231973248284, where AAG0ALLzmH will be the alias.

We have to pass valid alias name along with your url.( https://docs.branch.io/pages/links/integrate/#configure-deep-links )
![image002](https://user-images.githubusercontent.com/20103264/40342280-aeaf85b4-5d3e-11e8-832b-4ccd559b2b48.png)

**Comment by sequoiaat** [comment]
Hope this is ok now. We are closing it, please re-open if you are facing any issue.
