### ISSUE TITLE
Linking.openURL not working to open non branch link

### ISSUE THREAD

**Issue by adrianha** [BranchMetrics/react-native-branch-deep-linking#351]
Hi,
I've got an issue when i installed `react-native-branch-deep-linking`, **i cant navigate to my existing deep link using `Linking.openURL('myApp://user/1')`**. Current work around is using `branch.openURL('myApp://user/1')` and use `+non_branch_link` params to detect the desired url. is it expected behaviour to use branch.openURL instead of Linking.openURL to open non branch link?

Note: I'm using deep link to navigate in the app itself.

**Comment by sequoiaat** [comment]
Yes. It is not a workaround!!! You can handle non branch link using Branch library and is an expected behaviour.

Thanks

**Comment by adrianha** [comment]
Ok, thank you @sequoiaat . Well noted!
