### ISSUE TITLE
delayInitToCheckForSearchAds wipes out existing deeplink?

### ISSUE THREAD

**Issue by Jonovono** [BranchMetrics/react-native-branch-deep-linking#353]
Using RN branch version 2.3.0

This is the issue I am seeing:

1. I add Alert.alert(params) to branch.subscribe.
2. I send invite to myself from another device with app uninstalled, open link and wait on app store
3. Build app

Now. 
* If I have `[[Branch getInstance] delayInitToCheckForSearchAds];` running, when app gets built and run I see a popup for Branch for some generic apple search ad (I don't have `setAppleSearchAdsDebugMode` or anything test on). I don't see the alert for the actual link.

* If I remove that line I see the popup for the deeplink I sent in the alert

Is this expected? I would expect to see both? Or just the invite deeplink since I didn't come in through a apple search ad. Any idea why I get this sample search ad deeplink showing up? Is that expected?

Thanks~

**Comment by sequoiaat** [comment]
@Jonovono  It is expected behavior. We cross checked  the same on branch iOS native SDK and we got the same result .
