### ISSUE TITLE
Social login issue (e.g. Facebook) when integrating Branch deep linking

### ISSUE THREAD

**Issue by akbokha** [BranchMetrics/react-native-branch-deep-linking#357]
I am currently integrating the branch SDK into our application. Everything seems to be working well, but the integration somehow was blocking a social login callback.

Our users can sign in with their social media accounts. Everything goes well up until the step that onNewIntent(intent) is called. 

I initially thought that something was wrong in the manifest, but after some testing/debugging I came to the conclusion that the problem is in `onNewIntent(intent)`.

In the Branch Metrics docs (Android and React Native), one is instructed to override `onNewIntent(intent)` with the following code snippet:

```java
    @Override
    public void onNewIntent(Intent intent) {
        setIntent(intent);
    }
```

I inititally did not pay much thought to the missing super call since I assumed that there would be a good reason to ommit it. The `onNewIntent` method of the ReactActivity does not contain that much logic, which is why I didn't find it strange. 

However, adding the super call resolves the social login issue at my end. 
It also does not seem to effect the Branch deep linking functionality (tested afterwards), so I am wondering whether:

1. You could provide a reason behind the missing super call
2. Whether the super call can be added to the documentation if no valid reason is given at 1

**Comment by sequoiaat** [comment]
@akbokha Thanks for bringing it your attention.
1. Super call is required. Please refer to this example:
 https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/android/app/src/main/java/com/webview_example/MainActivity.java#L27
2. It needs to be updated in the documentation. I have requested for this.

**Comment by akbokha** [comment]
Ah, my bad. I overlooked the PR in which these documentation changes are reflected. Will close the issue.
