### ISSUE TITLE
RNBranch.redeemInitSessionResult() returns `result.params` as null

### ISSUE THREAD

**Issue by miljantekic** [BranchMetrics/react-native-branch-deep-linking#363]
Got an error from our staging application with the following error:

```
null is not an object (evaluating 'n.params.cached_initial_event=!0')
```

And narrowed it down to the following code:

```js
// ./src/index.js:45
if('params' in result) {
  result['params']['cached_initial_event'] = true
}
```

The issue is that the `params` property exists in the `result` object but is for some reason null and not an object resulting the above code throwing an error when setting the `cached_initial_event` property.

Fixed the issue in our app with adding a check that the `params` property is not null or undefined.

Additional info:
---
react-native Version: 0.52.0
react-native-branch: 2.3.3
Platform: Android 23

**Comment by jdee** [comment]
The related PR (#364) has been merged. In 3.0.0 we will revisit this and at least change the parameter name to conform with Branch morphology. This change will be released in a 2.3.4 patch.
