### ISSUE TITLE
Tracking methods undefined

### ISSUE THREAD

**Issue by stefanlenoach** [BranchMetrics/react-native-branch-deep-linking#365]
I'd like to disable tracking but using `branch.disableTracking(true)` throws `"undefined is not a function (evaluating _reactNativeBranch2.default.disableTracking(true))"`. Same thing happens when I try executing `branch.isTrackingDisabled`. Any ideas what the issue could be?

Here's the gist of what I'm doing in code:

```
import branch

export default class LinkManager {
   constructor() {
      branch.disableTracking(true)
      // branch.subscribe etc.
  }
}
```

**Comment by sequoiaat** [comment]
@stefanlenoach  Can you try this 

let disabled = branch.isTrackingDisabled()
      branch.disableTracking(!disabled)
 
In this case the value of disabled is showing as either true or false and it’s also working as expected.

**Comment by Wade-McDaniel** [comment]
Thanks! I'll give that a shot, but the exception seems to get thrown before I even use the disableTracking method, so my fingers are crossed.

One thing I did notice tho is that for Android disableTracking seemed to work fine.

**Comment by sequoiaat** [comment]
@Wade-McDaniel  Can we close this issue or should we investigate further ?

**Comment by Wade-McDaniel** [comment]
Thanks for checking with me! I believe you can feel free to close this. I changed around versions of other libraries I was using and I believe this problem went away on iOS...but that's relying on this old mans memory, so take that recollection with a grain of salt.
