### ISSUE TITLE
React Native installation instructions are not clear

### ISSUE THREAD

**Issue by econner** [BranchMetrics/react-native-branch-deep-linking#369]
From the RN installation instructions,

![image](https://user-images.githubusercontent.com/527947/44480020-0b4e8300-a5f7-11e8-8c1b-218f235a641d.png)

So there are two options.

Ok I'll go with Option 1. Try that and get `cannot find module react-native-branch` when trying to build

Reading further....
![image](https://user-images.githubusercontent.com/527947/44480086-376a0400-a5f7-11e8-8e6f-c5823f2789f8.png)

Am I installing >2.0.0? I guess I am.

Maybe these update instructions apply to me?

![image](https://user-images.githubusercontent.com/527947/44480068-2faa5f80-a5f7-11e8-8fee-7b85794cff7e.png)

Hmm... I guess I'm supposed to remove the packages I just installed?
![image](https://user-images.githubusercontent.com/527947/44480226-9465ba00-a5f7-11e8-970c-4c75b83e5947.png)

Hmm.. but I just added it using `react-native link`. What that correct? Or should I have done Option 2?

Maybe the Podfile is wrong? 

Checked Podfile and found that only
```
pod "react-native-branch", path: "../node_modules/react-native-branch"
```
was there.

So maybe I need 
```
pod "Branch-SDK", path: "../node_modules/react-native-branch/ios"
```
but this I am being told to remove?

Anyway I added that line and got a step further. Then encountered,
```
'React/RCTLog.h' file not found
```

Weird. Ok, 
![image](https://user-images.githubusercontent.com/527947/44480937-5c5f7680-a5f9-11e8-80ac-4148e7ac363c.png)

So am I supposed to be removing this config from the Podfile or adding it? There's a line there about removing CocoaPods entirely so maybe that means I don't need any pods?

Did something screw up with react-native link?

Ok maybe we can unlink and re-link:

```
react-native unlink react-native-branch
```

> rnpm-install info Unlinking react-native-branch android dependency
> rnpm-install info Android module react-native-branch has been successfully unlinked
> rnpm-install info iOS module react-native-branch is not installed
> react-native-branch info Removed Branch configuration from Android project
> /node_modules/xcode/lib/pbxProject.js:1813
>     return this.hash.project.objects['PBXVariantGroup'][key];
>                                                        ^
> 
> TypeError: Cannot read property '#<Object>' of undefined
>     at pbxProject.getPBXVariantGroupByKey (/node_modules/xcode/lib/pbxProject.js:1813:56)
>     at pbxProject.removeFile (/node_modules/xcode/lib/pbxProject.js:1943:19)
>     at removePathFromProject (/node_modules/react-native-branch/scripts/iosUtil.js:104:24)
>     at pbxProject.<anonymous> (/node_modules/react-native-branch/scripts/iosUtil.js:66:5)
>     at emitTwo (events.js:106:13)
>     at pbxProject.emit (events.js:191:7)
>     at pbxProject.<anonymous> (/node_modules/xcode/lib/pbxProject.js:31:18)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at process.nextTick (internal/child_process.js:752:12)
> /node_modules/react-native/local-cli/core/makeCommand.js:29
>         throw new Error(`Error occured during executing "${command}" command`);
>         ^
> 
> Error: Error occured during executing "node ./node_modules/react-native-branch/scripts/removeBranchConfig.js" command
>     at ChildProcess.prelink (/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:885:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Well that's not good. I hope that didn't break my project state.

Run 
```
react-native link react-native-branch
```

Oh, I guess it adds 
```
  pod 'react-native-branch', :path => '../node_modules/react-native-branch'
```
to the Podfile.

So maybe I do need that Branch-SDK line? Ok add that back.

Try `pod install`
> ...
> Installing React (0.11.0)
> ...
> [!] React has been deprecated

Ok, why is it adding React..do I need that?  And it is deprecated?

------

Anyway.... now I am getting:

```
'React/RCTLog.h' file not found
```

And am not sure why.

**Comment by gustavonecore** [comment]
The command `react-native link react-native-branch` works on your end?
After install I tried to run that, but nothing appears to be linked for branchio..

```
➜  app/path ✗ react-native link react-native-branch
Scanning 698 folders for symlinks in /Users/onecore/uprise/bopv2/BOP-White-Label/node_modules (17ms)
```

And after doing all the android setup steps I'm not able to build the project, since the branchio packages are not present, so all the related import fail.

Any idea @jdee / @econner  ?

Regards!

**Comment by econner** [comment]
Hey @gustavonecore ,

I did manage to get it to build eventually. `react-native link react-native-branch` worked for me for Android.

I believe you just need the following config:

```
diff --git a/android/app/build.gradle b/android/app/build.gradle
index 913fae3..257c192 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -172,6 +172,7 @@ android {
 }

 dependencies {
+    compile project(':react-native-branch')
     compile project(':react-native-splash-screen')
     compile project(':react-native-spinkit')
     compile project(':react-native-navigation')
     
diff --git a/android/app/src/main/java/com/yourappname/YourAppNameMobile/MainApplication.java b/android/app/src/main/java/com/yourappname/YourAppNameMobile/MainApplication.java
index 213faca..ed2ba64 100644
--- a/android/app/src/main/java/com/yourappname/YourAppNameMobile/MainApplication.java
+++ b/android/app/src/main/java/com/yourappname/YourAppNameMobile/MainApplication.java
@@ -55,6 +55,7 @@ public class MainApplication extends NavigationApplication {

         return Arrays.asList(
             new MainReactPackage(),
+            new RNBranchPackage(),
             new NavigationReactPackage(),
             new IntercomPackage(),
             new ImagePickerPackage(),

diff --git a/android/settings.gradle b/android/settings.gradle
index d383e61..2dd16a7 100644
--- a/android/settings.gradle
+++ b/android/settings.gradle
@@ -1,4 +1,6 @@
 rootProject.name = 'YourAppName'
+include ':react-native-branch'
+project(':react-native-branch').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-branch/android')
 include ':react-native-splash-screen'
 project(':react-native-splash-screen').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-splash-screen/android')
 include ':react-native-spinkit'
```

For iOS I had to completely deintegrate CocoaPods from my project before running `react-native link`.  See my comment here: https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/361#issuecomment-415149270

**Comment by gustavonecore** [comment]
Thanks man,

..well, I did get it working seeing the example app and doing the link process manually.

Nice tip about iOS, I'll be facing it after running some tests on android.

Regards!

**Comment by mradziwon** [comment]
Hi, I have a problem with RN build on Android. After `react-native link react-native-branch` I can't build project and error is `AGPBI: {"kind":"error","text":"Program type already present: io.branch.referral.AnimatedDialog$2","sources":[{}],"tool":"D8"}`. Any ideas why?

**Comment by dwilt** [comment]
@econner @jdee we're running into these exact same issues as well.. Why would `react-native link react-native-branch` modify the Podfile if that's the "Pure React Native" way?

**Comment by econner** [comment]
@sequoiaat Did you guys do anything to fix this?

**Comment by Sarkar** [comment]
@econner, no specific changes to this one -- we figured the workaround here would be OK for now. Is it continuing to come up?

**Comment by econner** [comment]
The workaround is ok, but it would be better I think to not have to deintegrate Cocoapods before trying to install this library. Is there a way to make the `.podspec` file play nicely? Or can you advise that we're doing something incorrectly when using Cocoapods?
