### ISSUE TITLE
Is there any doc/example for install a new fresh app from a branchio deeplink?

### ISSUE THREAD

**Issue by gustavonecore** [BranchMetrics/react-native-branch-deep-linking#370]
I was searching in the examples but I think all of them are related to already installed applications.
There is a lot of links, I have reviewed several of them but I can't find something for: 

- User open deeplink 
- User install app from play store
- App launchs with some custom data from the deeplink

Any suggestion will be good guys!

Thanks

**Comment by sequoiaat** [comment]
@gustavonecore  

Please let us know if this will help you answer your queries - 
**User open deeplink**
For this can you see if this document will answer this question you have. If not please let us know and we can try to help you 

**User install app from play store**
Can you please elaborate a little bit more  on this. Also see if this link anwers your query - https://docs.branch.io/pages/apps/react-native/#configure-branch 

**App launchs with some custom data from the deeplink**
Please see if this document is what you are looking for-  https://docs.branch.io/pages/apps/react-native/#navigate-to-content

**Comment by gustavonecore** [comment]
@sequoiaat Thanks for the insight, I was able to get it working.

But I'm facing some weird issue (this is my progress so far):
- I'm creating the deeplinks from my server using this tool: https://github.com/iivannov/branchio
- The deeplinks are created properly using the live keys and sent to the user as SMS

But this is the weird thing:

After the install my app launch with the custom data on it using this:

```
branch.getFirstReferringParams().then((params) => {

                if (params.phone && params['$deeplink_path'] === DEEPLINK_TYPE_INSTALL){
                        dispatch(Actions.fetchDeepLinkSuccess(params.phone));
                }
                else{
                    dispatch(Actions.fetchDeepLinkSuccess(''));
                }
        }).catch((error) => {
            dispatch(Actions.fetchDeepLinkSuccess(error));
        });

```
But, sometimes works and sometimes it doesn't. So, I have some assumptions/questions here:

- I know the deeplink have some timeout, but can I configure that?
- Is there some restriction between using several deeplinks por the same device ?
- Is there any issue for using the url (android) as `market://id=?app.example.id.com` instead of the web url `http://play.store.com/...` ? . By the way, I'm using the `market` one.
- Where I can see the deeplink created from my server in the branch console?

**Comment by csalmi-branch** [comment]
@gustavonecore are you still having issues, and do you still need help with those questions?

**Comment by csalmi-branch** [comment]
@gustavonecore is there anything else we can help you with here?

**Comment by csalmi-branch** [comment]
Due to the age and inactivity of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
