### ISSUE TITLE
Changelog Entries for 2.3.3

### ISSUE THREAD

**Issue by maxcodes** [BranchMetrics/react-native-branch-deep-linking#373]
It seems the [Changelog](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/ChangeLog.md) hasn't been updated since version 2.2.5.

This caused a lot of confusion when trying to figure out which SDK versions I was using. It'd be great to keep it up to date.

Thanks!

**Comment by aaaronlopez** [comment]
@maxcodes I sincerely apologize for the confusion! I just updated the ChangeLog https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/ChangeLog.md .

We'll ensure to update it with every new release!
