### ISSUE TITLE
Cannot read property STANDARD_EVENT_ADD_TO_CART

### ISSUE THREAD

**Issue by kelvinblade** [BranchMetrics/react-native-branch-deep-linking#375]
I am getting this getting when using import branch from 'react-native-branch' in the ios simulator but it works fine on the device.

How can I fix this? Thanks

**Comment by crbrasfield** [comment]
@kelvinblade I'm also getting this error. Did you manage to find a fix?

**Comment by thestoneoflapiz** [comment]
Having the same error, Anyone knows a solution?

**Comment by rodriguezmanu** [comment]
+1

**Comment by npedrini** [comment]
+1

**Comment by devautor** [comment]
I had my `getPackages()` function explicitly/manually set to the list of native packages, and following the tutorial, I had missed the same for `react-native-branch`. Doing this in `MainApplication.java` solved the error for me:
`import io.branch.rnbranch.RNBranchPackage;`
```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),

        // bugsnag
        BugsnagReactNative.getPackage(),

        // react-native-branch
        new RNBranchPackage()
      );
    }
```

**Comment by tarun29061990** [comment]
Any updates on this? I am getting this error in ios simulator

**Comment by abeddow91** [comment]
+1

**Comment by rodriguezmanu** [comment]
Have you tried ?

> react-native link react-native-branch 
> pod install
