### ISSUE TITLE
Crash when running on iOS 12 and Xcode 10

### ISSUE THREAD

**Issue by rplankenhorn** [BranchMetrics/react-native-branch-deep-linking#383]
```
<Error>: BPXLUUIDHandler Keychain Save Error: -34018: client has neither application-identifier nor keychain-access-groups entitlements
```

I checked that file above and found that it's inside this repo:  https://github.com/blackpixel/BPXLUUIDHandler.

**Comment by sequoiaat** [comment]
@rplankenhorn  you are correct branch doesn't  use BPXLUUIDHandler. We will close this issue.
