### ISSUE TITLE
generateShortUrl never resolves or reject

### ISSUE THREAD

**Issue by fega** [BranchMetrics/react-native-branch-deep-linking#384]
Hello, I'm stuck running the following code, the function buo.generateShortUrl() never resolves

``` javascript
static async createReferralLink(referralCode) {
    // only canonicalIdentifier is required
    const TITLE = 'title';
    const DESCRIPTION = 'description';
    const buo = await branch.createBranchUniversalObject('myAppName', {
      title: TITLE,
      contentDescription: DESCRIPTION,
    });
    const linkProperties = {
      feature: 'share',
      campaign: 'referral',
      stage: 'new user',
      alias: referralCode,
    };
    const controlParams = {
      $fallback_url: LANDING_URL,
      $og_title: TITLE,
      $og_description: DESCRIPTION,
      $og_image_url: BANNER_IMAGE,
      $desktop_url: IOS_URL,
      $ios_url: IOS_URL,
      $android_url: ANDROID_URL,
    };
    console.log(buo);
    const result = await buo.generateShortUrl(linkProperties, controlParams);
  }
```

it executes every time when the app starts.

**Comment by fega** [comment]
Hello @sequoiaat! thanks for oyur answer, what version did you use? latest?

**Comment by sequoiaat** [comment]
@fega we are using RN : 0.56 and React-native-branch:2.3.3

**Comment by aaggarwa88** [comment]
same Issue we are getting on latest version

**Comment by csalmi-branch** [comment]
@fega and @aaggarwa88 are either of you still experiencing this issue? If so, could you let me know what versions of RN and React-native-branch you are using, as well as which platforms (iOS, Android, etc.)?

**Comment by csalmi-branch** [comment]
Due to the age and inactivity of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!

**Comment by dmitryame** [comment]
This works for me on iOS, but never returns on Android, tried on different devices, always hangs the app after the call to generateShortUrl

**Comment by mljlynch** [comment]
did anyone resolve this? I'm hitting this on react-native 0.63.4 and react-native-branch 5.4.0

**Comment by dmitryame** [comment]
I'm waiting for the latest expo release, they seem to claim to be solving a lot of branch issues with the next release.

**Comment by mljlynch** [comment]
I'm using vanilla react-native which seems to have inconsistent support?
