### ISSUE TITLE
Create deep link with custom data branch.io (react-native)

### ISSUE THREAD

**Issue by Luckygirlllll** [BranchMetrics/react-native-branch-deep-linking#387]
I need to create a deep link with custom data, I want to add as a parameter userId, how can I do this?

My idea, was to use something like this: 
But this code didn't create any link at all 

```
 async shareReferralLink () {
    let linkProperties = {
      feature: 'share',
      channel: 'facebook',
      userId: "125",
  }

  let controlParams = {
       $desktop_url: 'http://desktop-url.com/monster/12345'
  }

  let {url} = await branchUniversalObject.generateShortUrl(linkProperties, controlParams)
  console.log("URL ", url)
}
```

**Comment by pcooney10** [comment]
Hi @Luckygirlllll, you can add the custom data when you create the `branchUniversalObject`.

The function takes two arguments,  _canonicalIdentifier_ (a string that uniquely identifies this item of content), and _properties_ (an object containing properties defining the Branch Universal Object):
`branch.createBranchUniversalObject(canonicalIdentifier, properties)`
You can read more [here](https://github.com/BranchMetrics/react-native-branch-deep-linking#create-branch-universal-object).

Using your example above, it'd look something like this (_depending on how you initially define the `branchUniversalObject`_):
```js
let branchUniversalObject = await branch.createBranchUniversalObject('canonicalIdentifier', {
  title: 'Cool Content!',
  contentDescription: 'Cool Content Description'}),
  contentMetadata: {
    customMetadata: {
      userId: "125", // your userId field would be defined under customMetadata
    }
  }
})

 async shareReferralLink () {
    let linkProperties = {
      feature: 'share',
      channel: 'facebook',
      userId: "125",
  }

  let controlParams = {
       $desktop_url: 'http://desktop-url.com/monster/12345'
  }

  let {url} = await branchUniversalObject.generateShortUrl(linkProperties, controlParams)
  console.log("URL ", url)
}
```

**Comment by sequoiaat** [comment]
@Luckygirlllll  We will close this if you still have an issue please feel free to reopen

**Comment by Infinitism** [comment]
This solution doesn't work. I tried retrieving the custom data using Branch.getLatestReferringParams() and it won't be passed into from there.

**Comment by hetmann** [comment]
@Infinitism I agree, it seems it doesn't pass to params.

I can see the customMetadata when decoding using the API `https://api2.branch.io/v1/url?url=___short-url___&branch_key=...`

Somewhere I'm missing something :)

**Comment by simistern** [comment]
did you manage to get this fixed
