### ISSUE TITLE
Is it possible to share branch.io deep link via own share function not branch.io function showShareSheet? (react native)

### ISSUE THREAD

**Issue by Luckygirlllll** [BranchMetrics/react-native-branch-deep-linking#388]
I checked example, and I see that deep links of branch.io are shared only via showShareSheet

Here is example which I found:

```
let shareOptions = { messageHeader: 'Check this out', messageBody: 'No really, check this out!' }
let linkProperties = { feature: 'share', channel: 'RNApp' }
let controlParams = { $desktop_url: 'http://example.com/home', $ios_url: 'http://example.com/ios' }
let {channel, completed, error} = await branchUniversalObject.showShareSheet(shareOptions, linkProperties, controlParams)
```
So my question can I share deep link via `react-native-share`, for example? Or I only can share it using branch.io function `showShareSheet` ?

**Comment by pcooney10** [comment]
Hey @Luckygirlllll, the `showShareSheet` method is not the only way to use the `branchUniversalObject`. There is the initial `createBranchUniversalObject` method ([docs](https://github.com/BranchMetrics/react-native-branch-deep-linking#create-branch-universal-object)):

```
import branch from 'react-native-branch'

let branchUniversalObject = await branch.createBranchUniversalObject('canonicalIdentifier', {
  locallyIndex: true,
  title: 'Cool Content!',
  contentDescription: 'Cool Content Description'}),
  contentMetadata: {
    ratingAverage: 4.2,
    ratingCount: 100,
    ratingMax: 5.0,
    customMetadata: {
      prop1: 'test',
      prop2: 'abc'
    }
  }
})
```

And then you can call `showShareSheet`, or `generateShortLink`. I think `generateShortLink` is what you may be looking for ([docs](https://github.com/BranchMetrics/react-native-branch-deep-linking#shortened-links)), but keep in mind that `showShareSheet` has some handy data in the callback:

- _completed_: success/cancelled
- _channel_: com.apple.UIKit.activity.Message, net.whatsapp.WhatsApp.ShareExtension, com.apple.UIKit.activity.CopyToPasteboard, or Copy (Android)

**Comment by sequoiaat** [comment]
@Luckygirlllll - We will close this. if you still have issue  please feel free to reopen
