### ISSUE TITLE
retrieve params parsing link

### ISSUE THREAD

**Issue by export-mike** [BranchMetrics/react-native-branch-deep-linking#394]
I have posters containing a QR code which is a branch.io url

I want to parse the given url so it doesn't trigger the react-native app to reload with the splashscreen.

this is bit of problem for me. is there a way to request to your API with the URL directly and get the parameters?

Thanks

**Comment by sequoiaat** [comment]
@export-mike   Please refer the documentation here - https://github.com/BranchMetrics/branch-deep-linking-public-api#viewing-state-of-existing-deep-linking-urls 

Let us know if you are facing any issues

**Comment by export-mike** [comment]
@sequoiaat Thanks I'm requesting the api directly myself.
However this is the react-native-deep-linking library, why isn't this apart of the library?
