### ISSUE TITLE
loadRewards for a unique user

### ISSUE THREAD

**Issue by abaddonGIT** [BranchMetrics/react-native-branch-deep-linking#396]
Hi guys. Tell me what I'm doing wrong. I call the branch method.setIdentity (visitorId), then make createBranchUniversalObject with the transition. But when I change the visitorId, it does not affect the number of points that the loadRewards method returns. How do I get points for a specific user ID? Checking everything on the IOS 11.4 emulator, react-native-branch - 2.3.0.

**Comment by sequoiaat** [comment]
@abaddonGIT - Can you please see if you can give branch method.setIdentity (visitorId)  before  the branch.subscribe method and see if you are still having the issue

**Comment by abaddonGIT** [comment]
Yes it fix the problem. Thanks
