### ISSUE TITLE
getLatestReferringParams doesn't work on iOS

### ISSUE THREAD

**Issue by smddzcy** [BranchMetrics/react-native-branch-deep-linking#399]
I create a short URL like this:

```js
const generateInviteLink = async () => {
  const branchUniversalObject = await branch.createBranchUniversalObject('someId', {
    locallyIndex: true,
    title: 'someTitle',
    contentDescription: 'someDescription',
    contentMetadata: {
      customMetadata: {
        promoCode: 'promoXyz',
      },
    },
  });
  const linkProperties = { feature: 'referral' };
  const { url } = await branchUniversalObject.generateShortUrl(linkProperties, {});
  return url;
}
```

Clicking the generated URL on an iOS phone opens the application correctly, but `getLatestReferringParams` doesn't work. It always returns `{+clicked_branch_link: false, +is_first_session: false}`.

```js
const branchParams = await branch.getLatestReferringParams();
// {+clicked_branch_link: false, +is_first_session: false}
```

Am I doing something wrong?

---

iOS version: 12.1
`react-native-branch` version: 2.3.3
branch.json: `{ "debugMode": false, "useTestInstance": false }`

**Comment by sequoiaat** [comment]
@smddzcy - Can you please ensure that ensure your app is using the live key instead of the test key . if there is a key mismatch this could happen

**Comment by smddzcy** [comment]
@sequoiaat I'm sure that we're using the live key. We just implemented our own flow for the referral flow since Branch wasn't working for us, but I will check `initSession` on Monday and let you know.

**Comment by smddzcy** [comment]
@sequoiaat Yeah apparently we forgot initiating the session in `AppDelegate.m`. Adding `[RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];` fixed the issue. Thanks a lot!
