### ISSUE TITLE
iOS branch.subscribe: params not reliably filled when app was closed beforehand

### ISSUE THREAD

**Issue by d-krueger** [BranchMetrics/react-native-branch-deep-linking#40]
Hi there,
first thanks for the building the react-native integration. That helps a lot!
It's working great for me with the exception of one case. Here is what I'm doing:

React Native Version: 0.31.0, RNBranch: 0.6.0, Branch-Pod: 0.12.5

1. Start the app
2. Double Tap Home and Swipe the app to close it.
3. Click Branch Link.
4. App opens fine but I get different behavior when I repeat the process for the same link:

Outcomes of step 4:
a) branch.subscribe callback is called with valid params
b) branch.subscribe returns {}

The process always comes out fine at 4 a) if I run the same (javascript) code in android. Therefore I assume it's an iOS integration issue. Also if I skip Step 2 and click the link while the app is in the background it works fine in iOS.

Initially I always got to 4b) in iOS and I was able to get this to work at least sometimes through changing the RNBranch.m file by adding: [[Branch getInstance] accountForFacebookSDKPreventingAppLaunch]; here:

`+ (void)initSessionWithLaunchOptions:(NSDictionary *)launchOptions isReferrable:(BOOL)isReferrable {
  [[Branch getInstance] accountForFacebookSDKPreventingAppLaunch];
  [[Branch getInstance] initSessionWithLaunchOptions:launchOptions isReferrable:isReferrable andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {`

Here is an excerpt of my AppDelegate.m: 

`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];

  [Localytics autoIntegrate:@"LLKey" launchOptions:launchOptions];
  [Localytics setLoggingEnabled:NO];

    NSURL *jsCodeLocation;

    Helper* helper = [[Helper alloc] init];
    NSString *bundleVersion = [helper getBundleVersionFromUserDefaults];
    NSString *urlString = [helper getAPIURL:bundleVersion];
    NSString *bundlePath = [helper downloadBundle:urlString];

    if (bundlePath != nil) {
        jsCodeLocation = [NSURL URLWithString:bundlePath];
    } else {
        jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
    }

      jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

    #if TARGET_IPHONE_SIMULATOR
        jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
    #else
        jsCodeLocation = [NSURL URLWithString:@"http://192.168.2.4:8081/index.ios.bundle?platform=ios&dev=true"];
    #endif

    RCTBridge *bridge = [[RCTBridge alloc] initWithBundleURL:jsCodeLocation moduleProvider:nil launchOptions:launchOptions];
    self.bridge = bridge;
    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"Yoloci"
                                                 initialProperties:nil
                                                     launchOptions:launchOptions];

    // Get launch image
    NSString *launchImageName = nil;
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPhone) {
        CGFloat height = MAX(RCTScreenSize().width, RCTScreenSize().height);
        if (height == 480) launchImageName = @"LaunchImage_480.png"; // iPhone 4/4s
        else if (height == 568) launchImageName = @"LaunchImage_568.png"; // iPhone 5/5s
        else if (height == 667) launchImageName = @"LaunchImage_667.png"; // iPhone 6
        else if (height == 736) launchImageName = @"LaunchImage_736.png"; // iPhone 6+
    }

    // Create loading view
    UIImage *image = [UIImage imageNamed:launchImageName];
    if (image) {
        CGSize s = RCTScreenSize();
        if (application.statusBarFrame.size.height == 40) {
            s.height = s.height - 20;
        }
        UIImageView *imageView = [[UIImageView alloc] initWithFrame:(CGRect){CGPointZero, s}];
        imageView.contentMode = UIViewContentModeBottom;
        imageView.image = image;
        rootView.loadingView = imageView;
    }

    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    UIViewController *rootViewController = [[UIViewController alloc] init];
    rootViewController.view = rootView;
    self.window.rootViewController = rootViewController;

    [self.window makeKeyAndVisible];

    return [[FBSDKApplicationDelegate sharedInstance] application:application
                                    didFinishLaunchingWithOptions:launchOptions];

}

- (void)applicationDidBecomeActive:(UIApplication *)application {
    [FBSDKAppEvents activateApp];
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {

    if (![RNBranch handleDeepLink:url]) {

      NSString* urlstring = [url absoluteString];
      if ([urlstring hasPrefix:@"fb"]) {
          return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                            openURL:url
                                                  sourceApplication:sourceApplication
                                                         annotation:annotation];
      }else{
        //do nothing - non-fb links should be handled through branch
      }
    }
    return YES;
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *))restorationHandler {
    [RNBranch continueUserActivity:userActivity];
    return YES;
}`

I would be happy to provide more information on this case, if you can give me a hint on how to properly debug this scenario as the debugger becomes detached whenever I close the app and the error only occurs when the app has been closed beforehand.

I also found following issue which seems to refer to a similar behavior:
[https://github.com/BranchMetrics/ios-branch-deep-linking/issues/366](url)

Regards
David

**Comment by rt2zz** [comment]
@d-krueger I just tested your reproduction steps against both branch 0.12.1 and 0.12.5 both are working. 

Possibly you are doing your test with your phone connected in debug mode? in this case the second launch will fail because the process has been killed. If this is the case I would recommend building in release mode and see if this resolves the issue for you.

**Comment by d-krueger** [comment]
@rt2zz 
I built the app in release mode and i get the same results. Sometimes params is filled and sometimes it's empty. Also it's not always the first open. Actually it's completely random sometimes it works for three tries in a row. Sometimes it doesn't work for three tries, sometimes it alternates between working and not working.

As I only got it to work by adding [[Branch getInstance] accountForFacebookSDKPreventingAppLaunch]; it seems to be some kind of race-condition to me maybe with some of the other Frameworks (Facebook SDK, Localytics SDK) I am using.
If you can point me how to debug this I would be happy to dig further into the iOS code. Since this only happens when I launch the app via the link I am not sure how to debug this (attach the debugger on app-launch through link).

**Comment by d-krueger** [comment]
@rt2zz 
I found following thread in the ios integration issue list. It was indeed an issue concerning Facebook SDK integration. Instead of inserting `[[Branch getInstance] accountForFacebookSDKPreventingAppLaunch]` I changed the `application:didFinishLaunchingWithOptions ` from this:

`
return  [[FBSDKApplicationDelegate sharedInstance] application:application
                                    didFinishLaunchingWithOptions:launchOptions];
`

to this:

`
[[FBSDKApplicationDelegate sharedInstance] application:application
                                    didFinishLaunchingWithOptions:launchOptions];
 return YES;
`

This solves the issue for me.

**Comment by lprhodes** [comment]
Thanks for this - I was seeing the same issue, a mention in the docs may be useful?

**Comment by rt2zz** [comment]
@d-krueger @lprhodes awesome!

Looking to update the docs now, can you clarify for me:
By default the react-native AppDelegate.m template has `return YES;` at the end of `application:didFinishLaunchingWithOptions`. Did the FBSDK integration recommend replacing that with `return [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions]; `?

Also with that method returning YES, does that obviate the need for `[[Branch getInstance] accountForFacebookSDKPreventingAppLaunch]` altogether?

I will definitely add a section in the readme for facebook sdk integration, but want to better understand the underlying issue first.

**Comment by d-krueger** [comment]
@rt2zz 

I double checked facebook integration guidelines. The newest version also recommends just to `return YES;` but I assume that the guidelines were different a year ago. see here https://developers.facebook.com/docs/ios/getting-started

`[[Branch getInstance] accountForFacebookSDKPreventingAppLaunch]` was not needed. Actually I recommend against using it as it produces unreliable (from my perspective random) results. `return YES` works reliable for me.

Unrelated to this issue: Also if you don't mind I would still appreciate some help with #41

**Comment by pesterhazy** [comment]
@d-krueger, you just save my team a day or more of banging our heads against the wall. Thanks! If you ever come to Berlin, send me a message -- we owe you a beer. Also thanks to @rt2zz for this great library!

**Comment by d-krueger** [comment]
@pesterhazy lol - never thought I would earn a beer through posting an issue in github. Starting to love the community here ;) Currently working out of Hamburg area - so I might take you up on your offer soon...

**Comment by pesterhazy** [comment]
Please do. Gmail and Twitter nicknames like github!
