### ISSUE TITLE
Not register install event

### ISSUE THREAD

**Issue by abaddonGIT** [BranchMetrics/react-native-branch-deep-linking#400]
Hi all. I'm trying to make the accrual of interest for the installation of the application. Both referrer and referring user have to be rewarded once app installed via link.
Rules for branch.io
![2](https://user-images.githubusercontent.com/3716060/49580652-7c286980-f960-11e8-97e8-f7d24a2b41ca.png)
Rewards points in app
![1](https://user-images.githubusercontent.com/3716060/49580695-96fade00-f960-11e8-8bbb-309aae8f7c17.png)
Generate referral link
![ac021dca-9ed4-4768-aa13-2e25d0198429](https://user-images.githubusercontent.com/3716060/49581406-f0640c80-f962-11e8-9b55-869154a9da8e.jpg)
Visitorid is stored in device’s keychain and not changing if app has been deleted.
Branch logout called when user resets visitorid and generate new one. The problem is that the install event is triggered in a strange way: it’s triggered once for single user and just one of users gets rewarded, even though rule states it has to happen every time for both parts.
What am I doing wrong?
And another question, can I somehow check the install event on the emulator in dev-mode?

**Comment by sequoiaat** [comment]
@abaddonGIT - Please check this and let us know if this helps you - https://docs.branch.io/pages/apps/react-native/#simulate-an-install

**Comment by csalmi-branch** [comment]
@abaddonGIT Are you still experiencing an issue, or did the link from @sequoiaat provide you with what you needed?

**Comment by csalmi-branch** [comment]
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
