### ISSUE TITLE
:app:transformDexArchiveWithDexMergerForDebug

### ISSUE THREAD

**Issue by jorgemarrero** [BranchMetrics/react-native-branch-deep-linking#404]
## Your Environment
* `react-native-branch` version: ^2.3.3
* Platform: Android
* OS version: Mac High Sierra 10.14.2
* React Native version: ^0.57.8

## Expected Behavior
It should build on the mobile device.

## Actual Behavior
Fails with this:

```
> Task :app:processDebugGoogleServices
Parsing json file: .../react-native/woonivers/android/app/google-services.json

D8: Cannot fit requested classes in a single dex file. Try supplying a main-dex list.
# methods: 65882 > 65536

> Task :app:transformDexArchiveWithDexMergerForDebug FAILED
```
## Steps to Reproduce

1. Run `yarn add react-native-branch`
2. Run `cp node_modules/react-native-branch/branch.example.json branch.json`
3. Run `react-native link react-native-branch`
4. Modify `compile` per `implementation` in build.gradle. All my dependencies:
```
dependencies {
    implementation project(':react-native-branch')
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-code-push')
    implementation project(':react-native-onesignal')
    implementation project(':react-native-svg')
    implementation project(':react-native-camera')
    implementation project(':react-native-languages')
    implementation project(':react-native-firebase')
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-keychain')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.firebase:firebase-core:16.0.3"
    implementation "com.google.firebase:firebase-auth:16.0.3"
}
```
5. Run `react-native run-android`

Please let me know if you find out something that I'm missing or doing something wrong.

Thank you so much,

**Comment by jdee** [comment]
Have you tried enabling multidex? Most production apps do that for just this reason. And for that reason, all the Android examples in the repo also enable multidex. This has nothing to do with Branch. It just happens when your app gets too big for one dex file.

https://developer.android.com/studio/build/multidex
