### ISSUE TITLE
Does not compile for release on android with RN 0.57

### ISSUE THREAD

**Issue by mieszko4** [BranchMetrics/react-native-branch-deep-linking#407]
When I compile this with new RN 0.57 I get the following errors:
```
> Configure project :react-native-branch 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
```
and
```
error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
/home/mieszko4/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/2894229df102aba6e62f0ed03c56206b/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.
    
/home/mieszko4/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/2894229df102aba6e62f0ed03c56206b/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.
    
/home/mieszko4/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/2894229df102aba6e62f0ed03c56206b/res/values-v26/values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
    
/home/mieszko4/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/2894229df102aba6e62f0ed03c56206b/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontStyle not found.
    
/home/mieszko4/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/2894229df102aba6e62f0ed03c56206b/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/font not found.
    
/home/mieszko4/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/2894229df102aba6e62f0ed03c56206b/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontWeight not found.
    
error: failed linking references.
```

This happens when I run for release (for debug it works ok)
I am using `com.android.tools.build:gradle:3.1.4`
As a workaround the following helps:
```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
```

**Comment by jdee** [comment]
I'm going to do a new release early next week that will fix this and at least some other minor issues. I've run into this and was just chatting with the Branch devs about it. For now I've had better luck on Android by installing the Branch SDK directly from Maven. If you want to try this, in the build.gradle within the react-native-branch project, use

```
implementation 'io.branch.android.sdk:library:+'
```

and in the app/build.gradle:

```
implementation 'io.branch.android.sdk:library:3+'
```

And in both cases remove/comment out the `implementation fileTree` line.

We'll have a more solid solution in place with the next release. Sorry for the trouble and the delay in getting back to you on this.

**Comment by jdee** [comment]
There is now a 3.0.0-beta.1 in NPM. See https://github.com/BranchMetrics/react-native-branch-deep-linking#updating-from-an-earlier-version. This addresses the issue by eliminating the jar from the package and taking the SDK from Maven directly. We still pin to a specific version. The results are the same.

3.0.0 will also introduce other features, including support for setting keys from JS instead of native configuration or branch.json. This will also be a breaking change.

For now, this should address the issue reported here. Please confirm, and I'll close this issue.

**Comment by mieszko4** [comment]
:thinking: I am having issue with installing v3.0.0-beta.1 from npm.
After running `npm remove react-native branch` and `npm i react-native-branch` I get the following error when building for android (`npx react-native run-android`):
```
> Task :app:compileReleaseJavaWithJavac FAILED
/home/mieszko4/my-app/android/app/src/main/java/com/myappreact/MainApplication.java:5: error: cannot find symbol
import io.branch.referral.Branch;
                         ^
  symbol:   class Branch
  location: package io.branch.referral
/home/mieszko4/my-app/android/app/src/main/java/com/myappreact/MainApplication.java:76: error: cannot find symbol
    Branch.getAutoInstance(this);
    ^
  symbol:   variable Branch
  location: class MainApplication
2 errors

FAILURE: Build failed with an exception.
```

Am I missing something?

**Comment by jdee** [comment]
@mieszko4 Did you see this? I suppose I should have included this in my earlier response. (Only I hadn't written it yet.)

https://github.com/BranchMetrics/react-native-branch-deep-linking#updating-from-an-earlier-version

You probably just need a change to your `app/build.gradle`.

**Comment by mieszko4** [comment]
Thanx @jdee! I must have missed this updating from an earlier version guide.

It builds well now on android so I will close this issue
