### ISSUE TITLE
Handling offline mode in app init

### ISSUE THREAD

**Issue by NirpE** [BranchMetrics/react-native-branch-deep-linking#408]
Hi,

Is there any way to proceed with app normal flow when airplane mode is on? I am facing following error with my Android device in the `subscribe` callback and user is unable to continue using app.

`E/unknown:ReactNative: Unable to launch redbox because react activity is not available, here is the error that redbox would've displayed: console.error: "Error from Branch: Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later."
`

Using branch version `^2.3.3`

**Comment by NirpE** [comment]
Issue was something else. This was just error seen in console. Closing.

**Comment by nenti** [comment]
Can you share what was wrong? Having similar issues.
