### ISSUE TITLE
android: subscribe callback delayed when app in foreground

### ISSUE THREAD

**Issue by d-krueger** [BranchMetrics/react-native-branch-deep-linking#41]
Hello Branch Team,
I'm using Localytics for in-app messaging. Localytics allows you to customize your call-to-action by supplying a url that is invoked upon pressing the call-to-action button. I would like to be able to use branch.subscribe to listen and respond to those events.

It seems that branch only invokes the callback, when the app is re-invoked. Here are the steps:

1. Open the app
2. Invoke an URL call from within the app
=> adb.logcat shows that intent is received and also the react native linking callback is triggered immediately - branch.subscribe is not triggered (in Android - it's immediately triggered in iOS)
3. I press the power button to put the app into background mode
4. I open the app again
=> Now branch.subscribe triggers the callback

I would like the branch.subscribe callback to be immediately triggered upon button press the same way as in iOS and react-native Linking. That way I can run the same code in android and iOS and can avoid using react native Linking. 

Regards
David

**Comment by rt2zz** [comment]
@d-krueger I will take a look at this and #40 today. Thanks for the detailed reports 👍

**Comment by d-krueger** [comment]
@rt2zz k - thanks a lot. Let me know, if you need further information.

**Comment by rt2zz** [comment]
What I suspect is happening is that when you tap the link while the app is open, the MainApplication onStart is never called, on onNewIntent is.

Can you try adding `RNBranchModule.initSession(this.getIntent().getData(), this);` to onNewIntent and see if that triggers?

(referencing step 2 of https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/setup.md#android-project)

**Comment by d-krueger** [comment]
@rt2zz 
Thanks for looking into this. If I change the onNewIntent to look like this:

`  public void onNewIntent(Intent intent) {
          this.setIntent(intent);
          RNBranchModule.initSession(this.getIntent().getData(), this);`

Then it actually triggers but it's not the end of the road yet unfortunately. In this case the callback triggers with: 

{error: null,
uri: 'https://MYBRANCHLINK',
params: null }

Then when I put the back into background and re-open it, then it triggers again with:

{error: null,
uri: 'https://MYBRANCHLINK',
params: {
... //params filled completely
} }

I would like to have the params filled in the initial trigger and would like to avoid the callback to be triggered again after the app is re-opened.

**Comment by sojanpr** [comment]
This sounds like  similar to the"newIntent()" delayed issue is with Android M+ devices. "onNewIntent()" is delivered after the  "onStart()" and hence the deep links params are  not received on by clicking a link an opening application from background.
Branch Native Android SDK added fix for this in below commit and released with v2.0.2
https://github.com/BranchMetrics/android-branch-deep-linking/commit/c3258842c9469c46b1f03213b606a3b07695da81

**Comment by sojanpr** [comment]
In the above case Branch init was called from onResume() in order to ensure "onNewIntent()" is called. @d-krueger could you please try calling  init in `onResume()` and update?

**Comment by rt2zz** [comment]
@sojanpr great info, right now we fix on v1.13.1, sounds like it is time for an upgrade. Test driving now: https://github.com/BranchMetrics/react-native-branch-deep-linking/tree/android-sdk-2

**Comment by d-krueger** [comment]
@sojanpr @rt2zz:
Thanks for your help. I integrated the fix implemented in the android-sdk-2 branch.

Now the branch callback is triggered when I have the init call in either `onResume()` or in `onNewIntent()` but in both cases params is empty. 
The version update prevented the callback from triggering again after re-opening the app from background.
So it fixes one part of the error (triggering twice) but I still need help on the empty params problem.

**Comment by rt2zz** [comment]
@d-krueger FYI I am on to something, I believe this is related to some setup's that worked with v1.x not working with branch sdk 2.x. Unfortunately there are a lot of moving parts here, but I am testing now and will get back to you tonight.

**Comment by rt2zz** [comment]
@d-krueger can you add

```java
  @Override
  public void onCreate() {
    super.onCreate();
    Branch.getAutoInstance(this);
  }
```
to your MainApplication.java file?

This is was not part of the react-native-branch 1.x docs, but is required for sdk 2.x

**Comment by d-krueger** [comment]
@rt2zz Did that - unfortunately that does not help :( I already published a new version of the app without this feature. If I have some time maybe next week, I will try to debug and hope to be able to provide some more detail.

**Comment by d-krueger** [comment]
Closing the issue because I could not get deep linking to work properly while the app is open and have since used another approach: I now use branch for all scenarios where the app is closed/not-installed and react native linking for whenever the app is open.

**Comment by shuzootani** [comment]
@d-krueger 
How did you do to get params using Linking(react-native)?
you might not remember how you did since it's long time ago.
