### ISSUE TITLE
"Trouble Sharing Link" on ShowShareSheet

### ISSUE THREAD

**Issue by owenhope** [BranchMetrics/react-native-branch-deep-linking#413]
On android this starting popping up and I can't get my share sheet to open anymore.

implementation

```
async function showShareSheet(leaderboardGroup) {
  AnalyticsService.trackWithProperties(AnalyticsConstants.userSharedPrivateLeaderboard,
    {
      leaderboardGroupId: leaderboardGroup ? leaderboardGroup.id : LEADERBOARD_GROUP_GLOBAL
    });

  let branchUniversalObject = await DangerZone.Branch.createBranchUniversalObject(
    `leaderboard_${leaderboardGroup ? leaderboardGroup.token : LEADERBOARD_GROUP_GLOBAL}`,
    {
      title: leaderboardGroup ? leaderboardGroup.name : 'Global' + ' Leaderboard',
      contentMetadata: {
        customMetadata: {
          leaderboardGroupToken: leaderboardGroup ? leaderboardGroup.token : LEADERBOARD_GROUP_GLOBAL
        }
      }
    }
  );

  let shareOptions = {
    messageHeader: leaderboardGroup ? leaderboardGroup.name : "Hunch",
    messageBody: `Join the ${leaderboardGroup ? leaderboardGroup.name : 'Global'} Leaderboard!`,
  };

  let linkProperties = { feature: 'leaderboard_share', channel: 'HunchApp' }

  console.log(branchUniversalObject);

  let {channel, completed, error} = await branchUniversalObject.showShareSheet(shareOptions, linkProperties);

  console.log(channel);
  console.log(completed);
  console.log(error);
}
```

```
[16:53:32] Object {
[16:53:32]   "_newIdent": [Function _newIdent],
[16:53:32]   "_tryFunction": [Function _tryFunction],
[16:53:32]   "generateShortUrl": [Function generateShortUrl],
[16:53:32]   "ident": "00e24cce-ce08-4da2-8e68-9d019e607144",
[16:53:32]   "listOnSpotlight": [Function listOnSpotlight],
[16:53:32]   "logEvent": [Function logEvent],
[16:53:32]   "registerView": [Function registerView],
[16:53:32]   "release": [Function release],
[16:53:32]   "showShareSheet": [Function showShareSheet],
[16:53:32]   "userCompletedAction": [Function userCompletedAction],
[16:53:32] }
[16:53:32] null
[16:53:32] true
[16:53:32] Trouble sharing link. Branch instance is not created. Make  sure your Application class is an instance of BranchLikedApp.
```

I am creating the object and then calling shareSheet on it, however I get this error back everytime. Detached expo project...Was working a few days ago and now not...

Any ideas? I don't quite get the Application class is an instance of BranchLikedApp...

**Comment by jdee** [comment]
Hi @owenhope. I doubt this is the exact problem, but the recommended way to do this anyway is to create the BUO in `componentDidMount` and save it as a property on your Component.

https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/src/Article.js#L33

And it's recommended to log a `ViewItem` BranchEvent after creating it.

https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/src/Article.js#L39

Then when it's time to show the share sheet, you should reuse the same instance.

https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/src/Article.js#L69

And it's not strictly required but a good idea to call `release()` on the saved BUO in `componentWillUnmount`.

https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/src/Article.js#L45

However, that's mostly a matter of optimization, and those things should not produce this error afaik.

Do you see any interesting log messages from the native layers? It's possible that will provide a hint, and if there's some useful information, maybe it just needs to be passed back to JS.

**Comment by owenhope** [comment]
@jdee thanks very much for your advice, I have refactored my code based off best practices.

The fix I found just now.... apparently I need to add my Branch Key to my AndroidManifest after detaching from Expo (Expokit 32) ... something that wasn't required earlier. I had been messing around in there with some other modules so probably was my own doing!

Cheers!
