### ISSUE TITLE
deep link properties parameters is empty in Android

### ISSUE THREAD

**Issue by MoeMamdouh** [BranchMetrics/react-native-branch-deep-linking#414]
I follow installation and link steps in [https://docs.branch.io/pages/apps/react-native/](url)
in **iOS** deep link working fine and data passes successfully
but in **Android** 
link open chrome then play store 
and sometimes open app directly but even parameters data is returned empty like this:

![screen shot 2019-02-06 at 12 44 27 pm](https://user-images.githubusercontent.com/16561058/52336217-021e6a80-2a0d-11e9-9609-a4460ce8ce3e.png)

should i update onStart() in MainActivity file?

![screen shot 2019-02-06 at 12 47 42 pm](https://user-images.githubusercontent.com/16561058/52336362-69d4b580-2a0d-11e9-9024-39419cf906e7.png)

and in Manifest.xml file this is right or should update it?
```
<application
   android:name=".MainApplication"
   ....
>
``` 
also when check 'web to app' the dashboard i found this:
<img width="805" alt="screen shot 2019-02-06 at 2 35 08 pm" src="https://user-images.githubusercontent.com/16561058/52341922-a22fc000-2a1c-11e9-880b-f9d2c116c200.png">

'"react-native-branch": "^3.0.0-beta.1",'
implementation "io.branch.sdk.android:library:3.0.4"

**Comment by deeptiBranch** [comment]
Hi MoeMamdouh, 
The reason you are facing this issue is that the basic setup has not been done properly. You have not entered a URI scheme on the link settings page. If you have not set up your app to support them, please review the documentation page on the subject. Kindly refer to this document to configure your dashboard: https://docs.branch.io/pages/dashboard/integrate/.  For react native setup, please refer the step by step guide from this doc: https://docs.branch.io/pages/apps/react-native/.

**Comment by MoeMamdouh** [comment]
Hi @deeptiBranch 
thank you for your reply,
but i already follow the document and also entered a URI scheme in the link settings page.
any help please?

**Comment by jdee** [comment]
Hi @MoeMamdouh. Have you compared your app with the examples in the repo, particularly 
[webview_example](https://github.com/BranchMetrics/react-native-branch-deep-linking/tree/master/examples/webview_example)? That's probably helpful. If you can't find a discrepancy there, could you please post all relevant sections of your AndroidManifest.xml? It should look something like this:

```xml
    <application android:name=".MainApplication" android:allowBackup="true" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:theme="@style/AppTheme">
        <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize" android:windowSoftInputMode="adjustResize" android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <!-- Branch intent-filter -->
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="rnwebview" android:host="open"/>
                <data android:scheme="https" android:host="ms9y.app.link"/>
                <data android:scheme="https" android:host="ms9y-alternate.app.link"/>
                <data android:scheme="https" android:host="ms9y.test-app.link"/>
                <data android:scheme="https" android:host="ms9y-alternate.test-app.link"/>
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity"/>
        <!-- Branch keys -->
        <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_gmvPhLx7x9cW5Qh4x80dVcphxviJom1r"/>
        <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_oaCHnPu3yWd42Pn2F4YfIgdlBAmPac1G"/>
    </application>
```

**Comment by MoeMamdouh** [comment]
thank you @jdee
Yes i already realize my fault but sorry forget to mention it and close the issue.
 in **AndroidManifest.xml** i  put schemes in to splash activity not in main activity. 
this was the problem.
