### ISSUE TITLE
Branch crash: setIdentity: Attempt to invoke virtual method... on a null object reference 

### ISSUE THREAD

**Issue by rahamin1** [BranchMetrics/react-native-branch-deep-linking#419]
Hi guys

I am using your package indirectly, through the expo.io interface (https://docs.expo.io/versions/latest/sdk/branch/)

Perhaps you can help... 
Here is the information:

https://github.com/expo/expo/issues/3546

**Comment by csalmi-branch** [comment]
Can you provide us with anymore details about your implementation? version numbers, etc.?

**Comment by rahamin1** [comment]
Please see all details in: https://github.com/expo/expo/issues/3546

**Comment by csalmi-branch** [comment]
@rahamin1 Can you double check that your keys are correct? This issue sometimes occurs with mismatched keys.

Another thing to check is that expo is calling the Branch functions in the correct order. It needs to call getAutoInstance() first to initialize.

**Comment by rahamin1** [comment]
Thanks! The customer of this app decided to go with another solution, therefore I stopped working on it and don't have the environment for testing. Closing this issue.
