### ISSUE TITLE
branch.json docs missing

### ISSUE THREAD

**Issue by levpopov** [BranchMetrics/react-native-branch-deep-linking#424]
Default install spews out:
`react-native-branch info branch.json not found. See https://rnbranch.app.link/branch-json for more information.`

The link resolves to a "Page not found" on GitHub

**Comment by jdee** [comment]
Sorry. That was accidentally removed from the repo. The link works now.

**Comment by csalmi-branch** [comment]
@levpopov I'm closing this issue as the link has been fixed. If you are still encountering this issue, please let us know.
