### ISSUE TITLE
Update React Native with latest Android library

### ISSUE THREAD

**Issue by aaustin** [BranchMetrics/react-native-branch-deep-linking#43]
It's using an old library: https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/android/build.gradle#L22

It should be safe to upgrade to the latest now.

**Comment by rt2zz** [comment]
we have been test driving latest for a while here: https://github.com/BranchMetrics/react-native-branch-deep-linking/tree/android-sdk-2

will PR after running through the test app
