### ISSUE TITLE
React Native - Xcode build fails after yarn & linking

### ISSUE THREAD

**Issue by kodayashi** [BranchMetrics/react-native-branch-deep-linking#435]
1. Add & Link the package

```
$ yarn add react-native-branch
$ react-native link react-native-branch
info Linking "react-native-branch" iOS dependency
info iOS module "react-native-branch" has been successfully linked
info Linking "react-native-branch" Android dependency
info Android module "react-native-branch" has been successfully linked
react-native-branch info branch.json not found. See https://rnbranch.app.link/branch-json for more information.
```

2. Build.

Error:

`/Users/me/my-app/node_modules/react-native-branch/ios/RNBranchProperty.h:9:9: 'Branch/Branch.h' file not found`

Using

```
"react-native": "0.59.4",
"react-native-branch": "^3.0.0-rc.1",
```

**Comment by kodayashi** [comment]
FYI same steps above with 2.3.5 works fine.

**Comment by gavrix** [comment]
How is Branch.framework supposed to be installed? I don't see ay reference of it installation instructions

**Comment by gavrix** [comment]
This started appearing in 3.0.0-rc1. I have 3.0.0-beta2 and it seems Branch SDK is part of RNBranch. There is no hint in installation instructions that Branch SDK was completely taken out.

**Comment by jdee** [comment]
https://github.com/BranchMetrics/react-native-branch-deep-linking/releases/tag/v3.0.0-rc.1
https://github.com/BranchMetrics/react-native-branch-deep-linking#updating-from-an-earlier-version-or-starting-with-v300

We'll get the docs updated.

**Comment by kodayashi** [comment]
Hi @jdee - With Branch 2.x we were able to leverage this product without pods (which introduces issues on the iOS side of things). Has support for a pure RN approach been dropped with 3.0.0, requiring pods only? What about an approach with Carthage (which is much less invasive for existing projects)? Thanks!
