### ISSUE TITLE
sdk v2.x does not work out of the box with setup instructions

### ISSUE THREAD

**Issue by rt2zz** [BranchMetrics/react-native-branch-deep-linking#45]
pending further investigation

**Comment by avishayil** [comment]
I made a fork of SDK version 1.3.0 and it works well, other SDKs failed for me.
I haven't tested them all, just 1.+ and 2.+, made a bet on 1.3.0 and it worked well.

**Comment by rt2zz** [comment]
Need to setup up Branch.getAutoInstance in MainApplication:
```java
  @Override
  public void onCreate() {
    super.onCreate();
    Branch.getAutoInstance(this);
  }
```
updated existing docs here https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/setup.md#android-project in the meantime while working on a more complete docs revamp

**Comment by aaustin** [comment]
Just updated our main docs at dev.branch.io with these changes as well.
