### ISSUE TITLE
Support for both Live/Test keys in RN

### ISSUE THREAD

**Issue by aaustin** [BranchMetrics/react-native-branch-deep-linking#46]
This might be more of a docs issue, but it'd be great to see how this is supported for both Android and iOS.

**Comment by kkav004** [comment]
It's not a docs issue, at least for iOS.
Currently, Live key is always used regardless whether you configured Test key or not.

There is getTestInstance method in Branch.m that returns Branch instance configured with Test key, but this method is not used anywhere and not exposed to Javascript: 
![image](https://cloud.githubusercontent.com/assets/1796670/19212791/8afde520-8db5-11e6-9475-c5d43d48e240.png)

**Comment by rt2zz** [comment]
just merged #55 which will allow using test instance. Still debating if this is worth exposing to js land or if it is better to keep the use of this api in native. I will play with the ergonomics a bit before cutting a release later this week.

**Comment by jdee** [comment]
This is now completely documented: https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/branch-environments.md

It is set up either according to Option 1 or Option 2 for all of the 2.0 examples in this repo, for both platforms:

- testbed_simple
- testbed_native_android
- testbed_native_ios
- webview_example
- webview_example_native_ios

The iOS setup for Option 2 is involved. This is something we can easily automate using the Fastlane plugin in this repo or other means.
