### ISSUE TITLE
Deep linking URL does not open app store

### ISSUE THREAD

**Issue by prabhaav** [BranchMetrics/react-native-branch-deep-linking#51]
I'm seeing a similar issue as with RN Branch [#454](https://github.com/BranchMetrics/ios-branch-deep-linking/issues/454)

![image](https://cloud.githubusercontent.com/assets/11723563/19116905/ec21d86c-8acb-11e6-9370-c49bbbfc51c3.png)

**Comment by aaustin** [comment]
Hey @prabhaav - That's not an issue with the RN package, but with the link service itself. Would you mind submitting your information along with the link that shows this behavior to https://support.branch.io? Thanks so much!

**Comment by prabhaav** [comment]
Thanks, the support team helped me find the solution. 

In case others run into this issue: I didn't need to set an $ios_url if it's setup in the link settings.
