### ISSUE TITLE
IOS: Install branch framework without pod

### ISSUE THREAD

**Issue by freiserg** [BranchMetrics/react-native-branch-deep-linking#52]
Hi!

Is there instruction how to install branch framework, don't use pod for IOS?

Thank you.

**Comment by prabhaav** [comment]
You can do a npm install, download the sdk and link it as described here: https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/18

**Comment by freiserg** [comment]
Thank you. I wouldn't like to edit source files. I want to use .xcodeproj instead of the .xcworkspace.
I've installed SDK from Pod and used this instraction:

1. Drag **/node_modules/react-native-branch/Pods/Pods.xcodeproj** into the **Libraries** folder of your Xcode project. ![](https://dev.branch.io/img/pages/getting-started/sdk-integration-guide/pod-import.png)

1. In Xcode, drag the `libBranch.a` Product from **Pods.xcodeproj** into your the **Link Binary with Libraries** section of Build Phases for your project’s target. ![](https://dev.branch.io/img/pages/getting-started/sdk-integration-guide/link-pod-binary.png)

**Comment by tarkanlar** [comment]
This is not working anymore I guess
