### ISSUE TITLE
showShareSheet: no og tags

### ISSUE THREAD

**Issue by pesterhazy** [BranchMetrics/react-native-branch-deep-linking#57]
Calling showShareSheet from a react native app, a link gets created, but when you open the link in the Facebook debug tool, it prints out the following warnings:

```
Inferred Property	The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.
Inferred Property	The 'og:title' property should be explicitly provided, even if a value can be inferred from other tags.
Inferred Property	The 'og:description' property should be explicitly provided, even if a value can be inferred from other tags.
Inferred Property	The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.
```

I'm basically following the "usage" section in https://github.com/BranchMetrics/react-native-branch-deep-linking

**Comment by pesterhazy** [comment]
I'm on `0.9.0` and am not seeing any errors. I'm setting `$fallback_url` FYIY.

**Comment by pesterhazy** [comment]
What is confusing, too, is that the documentation contained in the github README and the documentation on the Branch web site don't agree on how to call parameters. E.g.:

https://dev.branch.io/getting-started/branch-universal-object/guide/react/

mentions a `contentTitle` whereas the README docs, as well as the code (https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/966e82425746e100bb1d55619e65fdd24d88d4f9/ios/RNBranch.m#L107) claim it's called `title`.

**Comment by rt2zz** [comment]
a) thank you good catch, it should indeed by title. It was already correct further down in docs, but I just updated the usage example to match. I will be sure to update https://dev.branch.io/getting-started/branch-universal-object/guide/react/ to match as well.

b) great question, looking for some guidance upstream: https://github.com/BranchMetrics/ios-branch-deep-linking/issues/510. lets see what they say and go from there.

In the meantime I am assuming these warnings are not a blocker for you as the underlying functionality should continue to work. Please correct me if I am wrong!

**Comment by aaustin** [comment]
Hey @pesterhazy - The OG tags are actually unrelated to the RN package. The Branch link service manages the header files that get sent back to the scraper. A couple gotchas:
1. If you specify $fallback_url and no title, description or image url, Branch will forward the Facebook robot to your $fallback_url to find OG information.
2. If you specify a $fallback_url WITH title, description and image url, Branch will host your metadata when Facebook scrapes, specifying what you've given us via the Branch Universal Object.

I'm going to close this issue out here but happy to help get your links working for your use case.

**Comment by pesterhazy** [comment]
@aaustin, @rt2zz, thanks for the replies. For posterity, I got it to work by specifying $desktop_url and $android_url instead of $fallback_url.
