### ISSUE TITLE
+clicked_branch_link is returning undefined when clicking a branch link in iOS

### ISSUE THREAD

**Issue by seque1990** [BranchMetrics/react-native-branch-deep-linking#59]
We are trying to analyze where the users come from with branch's getLatestReferringParams, however in iOS the params for `['+clicked_branch_link']` is always `undefined` when the the actual sessions comes from a branch link, this problem is only happening with iOS (it's working with Android), and we have also tested trying to open this link via Chrome in the iPhone and it worked. I'm not completely sure if it's related to something going on with Safari or with the OS versions. Any guideline would be very welcome. Thanks

Here is a small snippet of the code we are trying to implement

```
        const lastParams = await branch.getLatestReferringParams()
        const comesFromBranchLink = lastParams['+clicked_branch_link'] # Giving us undefined when it comes from a branch link
        const isAReferralLink = lastParams['~feature'] === 'referral'
```

Edit:

We tested again and basically it doesn't recognize the branch link, only if it comes from Google Chrome.

**Comment by rt2zz** [comment]
Interesting, I have not come across this before. Are you on iOS 10? I will give this a spin tomorrow to see if I can replicate.

**Comment by srijan02420** [comment]
@rt2zz any luck. Not taking to app in safari for me also. Working fine in chrome.

**Comment by jdee** [comment]
Hi @srijan02420. @rt2zz Isn't responsible for this project anymore, though he might have some insights. I got started on it this week, so I'm still coming up to speed. I'll have an answer for you soon, probably early next week, unless I come across something obvious today. I appreciate your patience.

**Comment by srijan02420** [comment]
@jdee myapp://open?link_click_id=12345 is working for safari but branch marketing link is not taking to iOS app.

**Comment by jdee** [comment]
@srijan02420 I don't immediately reproduce your problem. I'm running the Branch testbed app on an iPhone 7+ with iOS 10.2, Branch SDK 0.12.23 and react-native 0.40.0.

This code produces expected results:

```JavaScript
branch.subscribe((bundle) => {
  if (bundle && bundle.params && !bundle.error) {
    console.log("Opened Branch link")

    const clickedBranchLink = bundle.params["+clicked_branch_link"]
    console.log("+clicked_branch_link: " + clickedBranchLink)

    branch.getLatestReferringParams().then((params) => {
      console.log("Last referring params: " + params)

      const clickedBranchLink = params["+clicked_branch_link"]
      console.log("+clicked_branch_link: " + clickedBranchLink)
    })
  }
})
```

It consistently produces this output when I open a marketing link from the Branch portal:

```
2017-01-09 14:26:06.733 [info][tid:com.facebook.react.JavaScript] Opened Branch link
2017-01-09 14:26:06.733 [info][tid:com.facebook.react.JavaScript] +clicked_branch_link: true
2017-01-09 14:26:06.735 [info][tid:com.facebook.react.JavaScript] Last referring params: [object Object]
2017-01-09 14:26:06.735 [info][tid:com.facebook.react.JavaScript] +clicked_branch_link: true
```

Also, your most recent comment indicates that a marketing link is not opening the iOS app. This is usually done by the OS using Universal Links to your Branch domain (*.app.link or custom domain). Also, the user can choose to open those links either in Safari or in the app. If you have previously tapped the breadcrumb with your domain name on the right side of the status bar, iOS will not open the app. You can usually use the Smart Banner in Safari to redirect to the app again, or there are other methods.

**Comment by jdee** [comment]
Also, @seque1990, I didn't at first realize there were multiple people commenting on this ticket, but you were the one with the original issue. Please see the comment above.

**Comment by seque1990** [comment]
Hello again @jdee, sorry to bother you again. I have been facing some inconsistencies when trying to analyze a deep link again (Only in iOS).

This is the link that I'm working with: https://beek.app.link/UAsxvtqxeC
It has the following metadata:

```
     metadata: {
        object: 'Book',
        bookID: 363,
      },
```

I am testing the link in an iPhone 6 emulator, iOS 10.2 and I'm using Gmail to click on the link, according to this document, the branch links are supposed to be consistent using Gmail: https://dev.branch.io/getting-started/universal-app-links/support/ios/#appsbrowsers-that-support-universal-links

So, here are the results of my testing:

**_When Rebooting the emulator / App Closed:_**
- The first time I clicked, I get `undefined` in `objectScene`
```
        const lastParams = await branch.getLatestReferringParams()
        const objectScene = lastParams['object']
```
- I clicked back in the top left Safari back button:
- Clicked again and get `undefined` again, back button in Safari.
- The third time I clicked in the link, it recognizes de link and I get redirected to the intended Scene.

**_Open App / Close App:_**
Same behavior as before, didn't work the first two times and worked in the third one.

**_App Open in the background:_**
Sometimes it worked in the first click, sometimes got `undefined` in the first clicked and worked as intended in the second link click.

I would like to get a better understanding of why this is happening and a guideline of where to look to solve this.

Thanks again.

**Comment by jdee** [comment]
@seque1990 Sorry you're having trouble. If Universal Links work on an iOS simulator, that's news to me. Maybe iOS 10 supports UL in the simulator, but I wasn't aware. I recommend testing on a device.

I'm not sure how you're using getLatestReferringParams. It might be worth noting that this method is essentially synchronous. It's just that it calls the native layer, and RN only supports asynchronous calls, using promises. If you just want to be called back when a link is opened, use `branch.subscribe`. The `params` argument in that callback is the same as the return value of `getLatestReferringParams`, only it's already there, and you don't have to await a promise. I can definitely say that if you just want to show the correct view in your app when a link is clicked, `getLatestReferringParams` is the wrong way to do it.

For a boilerplate example of handling and routing links in an app, please see the webview_example in this repo, particularly [App.js](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/src/App.js#L14). That uses the $canonical_url field and $og_title params to route links, but you can use custom metadata or whatever you like.

If this doesn't get you where you need to be, can you provide more context about how/when you're calling the SDK and/or what you're trying to do with getLatestReferringParams?

**Comment by seque1990** [comment]
Hello again @jdee, thanks for the quick reply, I wasn't aware of `subscribe` before. I tried changing the logic from using `getLatestReferringParams` to `branch.subscribe` with something like this:

```
        branch.subscribe(({ params }) => {
          if (params) {
            const objectScene = params['object']
            if(objectScene === 'Quote') {
              const bookID = params['bookID']
              navigator.push(getQuotesRoute(bookID))
            } else if (objectScene === 'Book') {
              const bookID = params['bookID']
              navigator.push(getBookRoute(bookID))
            } else if (objectScene === 'Shelf') {
              const shelfID = params['shelfID']
              navigator.push(getLibraryRoute(shelfID))
            }
          }
        })
```

Basically I'm just trying to check where the link where it comes from and get it to the right _Scene_, and if it doesn't fit anywhere it just stays in the HomeScene.

I encounter the following issues (We are on React Native 0.34.1 by the way):

In iOS:

a) **_If the App is open:_**
* Works like a charm.

b) **_If the App is closed:_**
* First time I clicked the App it stays in the HomeScene and nothing happens.
* Clicked back in the top left Safari icon and the clicked again, and this time it runs twice and pushes to the right route twice.

In Android:
c) **_If the App is open:_**
* First time I clicked, runs the subscribe callback twice and pushes the route twice.

d) **_If the App is closed:_**
* Works as intended.

I guess I can use some logic to work with `getLatestReferringParams` for Android and `subscribe` in iOS to make it work in case **a**, **c** and **d**. I'll just need help figuring out case b. 

Thanks again for your help.

**Comment by kafejo** [comment]
I get into same issue if I create a deeplink without specifying the type

```
## Request 
curl -X "POST" "https://api.branch.io/v1/url" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "branch_key": "key_live_abcdefg",
}'
```
When inspected the returned deeplink via `?debug=1` it has `xxx://open?link_click_id=link-undefined`. But then I add `type=2` (documentation says by default type is 0)

<img width="568" alt="image" src="https://user-images.githubusercontent.com/4762172/85843341-f0bc3680-b798-11ea-8b5a-6ff18a4ce567.png">

```
## Request 
curl -X "POST" "https://api.branch.io/v1/url" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "branch_key": "key_live_abcdefg",
  "type": "2"
}'
```

This produces correct deeplink with `xxx://open?link_click_id=link-804994711630187234`
