### ISSUE TITLE
is there branch.unsubscribe? 

### ISSUE THREAD

**Issue by good2hear** [BranchMetrics/react-native-branch-deep-linking#62]
Hi there,

I'm using branch.subscribe for incoming links as shown in usage
and wondering if there is branch.unsubscribe? i tried it with branch.unsubscribe and it doesn't seem to work. 

I need it in case when user is currently logged out and app is opened using deep link
it won't direct to the deep link page until user logs in

Thanks!

**Comment by rt2zz** [comment]
the `subscribe` method returns an unsubscribe function, much like redux does. i.e.
```
const branchUnsubscribe = branch.subscribe(listener)
// sometime later ...
branchUnsubscribe()
```
