### ISSUE TITLE
[android] launchMode singleTask needed?

### ISSUE THREAD

**Issue by good2hear** [BranchMetrics/react-native-branch-deep-linking#65]
Hello,
I'm wondering if launchMode:"singleTask" is necessary for android setup as below doc states 
(https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/setup.md) 
I have a conflict in AndroidManifest file due to another launchMode using singleTop

so tried without using singleTask and deeplink seems to work fine.
Will there possibly be any side effects of not using singleTask as launchMode in AndroidManifest?

appreciate any comments! 
Thanks!

**Comment by rt2zz** [comment]
@good2hear I do not have a definitive answer for you. The recommendation comes from https://github.com/BranchMetrics/android-branch-deep-linking#register-an-activity-for-direct-deep-linking-optional-but-recommended

IIRC singleTop is supported, just make sure you are handling onNewIntent. Here is a reference issue https://github.com/BranchMetrics/android-branch-deep-linking/issues/349.

I am curious as well to get to the bottom of this, and have opened a corresponding issue upstream at https://github.com/BranchMetrics/android-branch-deep-linking/issues/367

**Comment by good2hear** [comment]
@rt2zz thanks a lot!! i'll refer to your links and keep my eyes on issue you opened

**Comment by rt2zz** [comment]
https://github.com/BranchMetrics/android-branch-deep-linking/issues/367#issuecomment-267982681

Sounds like you should be ok using singleTop with the awareness that there may be additional complexity if you end up with multiple instances of the same task. 👍

**Comment by mcorner** [comment]
Sorry to dredge up an old issue, but we have been using singleTop as well.  I just noticed some of this complexity, which is:

1) Launch the app from the launcher.
2) Launch the app from another app using a link (like the messages app).

This gives you two tasks (I think this is the right term) so things like branch's subscribe callbacks end up getting fired twice.  If I switch to singleTask I don't get that behavior, but I don't know what effects this has on things that require singleTop (like FCM).

**Comment by n-sviridenko** [comment]
@mcorner have you had any issues with FCM or other libraries when using `singleTask`? Or you decided to keep `singleTop`? We use expo SDK (detached). Is there anyone having a similar situation?

**Comment by mcorner** [comment]
@n-sviridenko We have been using singleTask for a long time.  We use quite a number of libs (but not branch anymore).

**Comment by n-sviridenko** [comment]
Is there anyone using branch and FCM? How did you manage `singleTask` vs. `singleTop` dilemma?

**Comment by n-sviridenko** [comment]
Having this error with `5.2.5` and RN `0.55.4`:
```
Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints: 
   Dependency path 'android:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-functions:16.1.3' --> 'com.squareup.okhttp:okhttp:2.7.5' --> 'com.squareup.okio:okio:1.6.0'
   Dependency path 'android:react-native-firebase:unspecified' --> 'com.google.firebase:firebase-firestore:17.1.5' --> 'io.grpc:grpc-okhttp:1.16.1' --> 'com.squareup.okio:okio:1.13.0'
   Dependency path 'android:react-native-firebase:unspecified' --> 'com.facebook.react:react-native:30.0.0' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.0.1' --> 'com.squareup.okhttp3:okhttp:3.0.1' --> 'com.squareup.okio:okio:1.6.0'
   Constraint path 'android:react-native-firebase:unspecified' --> 'com.squareup.okio:okio' strictly '1.6.0' because of the following reason: debugRuntimeClasspath uses version 1.6.0
   Constraint path 'android:react-native-firebase:unspecified' --> 'com.squareup.okio:okio' strictly '1.6.0' because of the following reason: debugRuntimeClasspath uses version 1.6.0
```
Regarding RN:
```
"react-native@https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz":
  version "0.55.4"
```

**Comment by n-sviridenko** [comment]
Downgraded to `4.3.8` (expo `30.0.0` uses grandle `3.1.4` which is lower than the one which is used in RNFB `5.2.5`).
