### ISSUE TITLE
[iOS] extra setting due to Branch/Branch.h not found

### ISSUE THREAD

**Issue by good2hear** [BranchMetrics/react-native-branch-deep-linking#66]
Hello,

I was able to get iOS working (using cocoa pod) after adding some extra setting (adding header search path in RNBranch.xcodeproj, switching to #import <Branch-SDK/Branch.h> in RNBranch.m, etc) 

then the problem is that when I upload it on github; my colleague downloads it to work on something else, he has to do that setting again (search path, switching import, etc) besides npm install and pod install in order not to get build error.. meaning these setting in RNBranch.xcodeproj and RNBranch.m are not saved in github. 

wondering if there is a way to avoid this problem.

any comments will be appreciated!!

**Comment by good2hear** [comment]
ah just saw PR created by @theseansy regarding this issue, I guess we just need to wait for this PR to be merged?

**Comment by jdee** [comment]
@good2hear This was addressed in 1.0.0, which was released Friday. There should be no special settings required, and the instructions have been updated. Closing this issue.
