### ISSUE TITLE
Documentation for Google Analytics and Mixpanel Integration

### ISSUE THREAD

**Issue by blackburnian** [BranchMetrics/react-native-branch-deep-linking#78]
We have a React Native app out for both iOS and Android.  We need to integrate Branch with both Google Analytics and Mixpanel.  There are guides here describing how to set up integrations for native apps:
https://dev.branch.io/third-party-integrations/google-analytics/guide/
https://dev.branch.io/third-party-integrations/mixpanel/guide/

These guides however do not describe how to set it up for React Native.  Can you provide guides for these scenarios?

**Comment by jdee** [comment]
@blackburnian Sorry for the delay. A RN version of those instructions sounds like a good idea. I'm not very familiar with those integrations, but I think you can probably just follow the native instructions and add the code to the native portions of your RN app. For example, make the specified changes in the AppDelegate.m in your Xcode project and in the MainActivity or MainApplication in your Android project. Please feel free to ask here for further help or advice. We can do something about the documentation as well.
