### ISSUE TITLE
Integration Issues

### ISSUE THREAD

**Issue by Zidail** [BranchMetrics/react-native-branch-deep-linking#83]
```
React-Native: 0.39
Xcode: 8.2.1
iOS: 10.2
Branch: 1.0.0
```

**Please forgive me if i'm missing some core fundamentals of objective-c / iOS Programming**

I seem to be having troubles with the integrating this into an existing react-native project.
I've followed the instructions listed here: [https://dev.branch.io/getting-started/sdk-integration-guide/guide/react/](https://dev.branch.io/getting-started/sdk-integration-guide/guide/react/)

## Issue 1: `Lexical or Preprocessor Issue 'React/RCTBridgeModule.h' file not found`

I am currently getting the error `Lexical or Preprocessor Issue 'React/RCTBridgeModule.h' file not found`.

I've resolved the issue by doing the following:
- Adding `$(SRCROOT)/../../react-native` to the `Header Search Paths` in the RNBranch `Build Settings`.
- Changing the header imports from `<React/RCTBridgeModule.h>` to `RCTBridgeModule.h` in the header files.

My current setup does not include adding `React` as a podfile. Looking back through the history of the file, it seems like it was removed recently (16 days as of writing this).

## Issue  2: Semantic/Parse issues

Seems like the C++ is causing some issues for me. Got a whole bunch of errors saying `Could not build module 'xxxx'`, namely `CoreFoundation`, `Foundation` and `CoreGraphics`.

I've resolved the issue by doing the following:
- Changing `Compile Sources As` in `RNBranch` from `According to File Type` to `Objective-C++`

## Issue 3: Variable Declarations

I'm getting quite a few issues with mismatching var types, i.e.
- `redeemRewards:(Integer *)amount` on line `293` of `RNBranch.m`. When it passes it to `[branchInstance redeemRewards:forBucket:callback:]`, the method expects it without the pointer in lines `299` and `308`.
- `errorMessage = error` on line `34` of `RNBranch.m`. Mainly assigning `NSError` to an `NSString`.
- Multiple assignments of `[NSNull null]` instead of using `nil`. If we take a look at line `30`, `NSString *errorMessage = [NSNull null]` keeps giving me the red bubble.

**Is this the correct way to resolve the issue, or am i perhaps missing a step in the integration process?**

Thanks everyone!

**Edit: I've encountered a bit more issues down the line when trying to deploy onto an actual device, so i split it into separate issues**

**Comment by jdee** [comment]
Hi @Zidail. `react-native-branch@1.0.0` requires `react-native@0.40.0`. I'm surprised you were able to install 1.0.0 with RN 0.39 in the same project, since the `react-native` requirement in the package.json for 1.0.0 is `^0.40.0`.

If you cannot update to RN 0.40, please limit `react-native-branch` to `~0.9.0`. (There was an accidental release 0.10.0, which is identical with 1.0.0 and won't work with RN 0.39.)

There will be a 0.9.1 release this week. You can also try this branch in the repo: `release-0.9.1`.

If you have trouble integrating 1.0 with RN 0.40 or 0.9 with RN < 0.40, please let us know.

**Comment by Zidail** [comment]
Thanks for the answer @jdee.

Seems like RN 0.40 changes all the imports and most of the npm packages that i use haven't been update for it yet, so using the `0.9.0` version of branch does seem like the best idea.

Thanks again for all the help. I'll be closing this issue now.
