### ISSUE TITLE
[iOS]: Upgrading to 1.0.0 (RN 0.40.0) fails

### ISSUE THREAD

**Issue by dwilt** [BranchMetrics/react-native-branch-deep-linking#88]
Went through all of the installation instructions in full multiple times and I keep ending up with this: `ld: library not found for -lRNBranch` when trying to build:

![image](https://cloud.githubusercontent.com/assets/1065539/22414680/521c52f4-e676-11e6-9fb6-94000d26780e.png)

**Comment by jdee** [comment]
@dwilt It looks like you're using CocoaPods. Three questions:

1. Are you using the React pod in your Podfile or just taking the native React projects from the Libraries group?
2. Do you have `use_frameworks!` in your Podfile?
3. Is the RNBranch project included in your Libraries group like this?
![RNBranch at end of Libraries](https://raw.githubusercontent.com/BranchMetrics/react-native-branch-deep-linking/master/docs/assets/RNBranch.png)

I'm not sure what might cause this failure, but hopefully this information will help.

**Comment by bsy** [comment]
Running into this as well, just upgraded to RN 0.40
1) Using Podfile, Branch (0.12.16) was installed, previously I had locked to ranch Branch (0.12.11)
2) Not using `use_frameworks!` in the Podfile
3) Yes the RNBranch.xcodeproj is in the my Libraries

**Comment by bsy** [comment]
I just resolved this by manually installing the `RNBranch.xcodeproj` to the Libraries folder, and added the `libreact-native-branch.a` to the Link Binary With Libraries section.  Running `react-native link` didn't work for `1.0.0`.

**Comment by jdee** [comment]
Hi @bsy. I'm glad you were able to resolve it. I'm not sure why `react-native link` didn't work for you. 
Also, if `RNBranch.xcodeproj` was already in your Libraries group, I'm not sure what was missing before.

And I'm not sure how you ended up updating from version 0.12.11 to 0.12.16 of the Branch SDK. If you didn't run `pod update`, there would be no change. If you ran `pod update` in the last couple of weeks, it should have updated at least to 0.12.24. In general, there's an issue with trying to keep the NPM module and the native Branch SDKs in synch. I have plans for addressing that in a later release. For now, it's probably a good idea to run `pod update` from time to time. I think Gradle may make things a bit simpler for Android, but there can be a similar issue there.

**Comment by dwilt** [comment]
@bsy Thanks, I'll try that out when we officially upgrade. There are a couple of plugins that we rely on which haven't upgraded to support `0.40.0` so we're shit out of luck at the moment.

@jdee to answer your questions:

1 & 2. We're using the Podfile, and we are not using the `use_frameworks!` either.
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

workspace 'GreatJonesStreet.xcworkspace'
project 'GreatJonesStreet.xcodeproj'

pod 'OneSignal', '~> 1.13.2'
pod 'Branch'
pod 'Mixpanel'

target 'GreatJonesStreet-Dev'
target 'GreatJonesStreet-Prod'
```
3. Yes it is.

**Comment by jdee** [comment]
@dwilt @bsy I think I know what happened here. In 1.0.0 the library name changed from `libRNBranch.a` to `libreact-native-branch.a`. You probably only need to change the name of the library in your dependencies.

<img width="571" alt="screen shot 2017-01-31 at 11 44 23 am" src="https://cloud.githubusercontent.com/assets/121951/22481606/bf737adc-e7aa-11e6-9290-2081aff6e99f.png">

I think you can also remove RNBranch.xcodeproj from the Libraries group and then run `react-native link` to add it back with the proper library name.

I forgot to add that to the [update instructions](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/updating-1.0.0.md). I'll do that now.

Finally, the two testbed apps, testbed_carthage and testbed_cocoapods, both build and run. You can also use those (the latter, in your case) as guides in case it helps.

**Comment by bsy** [comment]
@jdee I think originally I had copied over my Podfile config from another app, which is why i was locked to 12.11 previously, and then I recall just removing the version lock and running `pod install` instead of `pod update`.  On top of this, I just re-tested running `react-native link` after removing `RNBranch.xcodeoproj` and `libreact-native-branch.a` file.. and things just worked fine, so not sure what might have caused the issue previously. 

@dwilt feel for you re: dependencies!  btw, I noticed you're using the 1.x version OneSignal like I was previously, I just upgraded to the latest `react-native-onesignal` and OneSignal Podfile and have iOS up and running just fine!  Testing Android later today.

**Comment by jdee** [comment]
@bsy That makes sense. As of 1.0, CocoaPods no longer updates pod repos on `pod install`. You can use `pod install --repo-update` or `pod repo update; pod install` to make sure you get the latest version of everything. You must have had 0.12.16 in your local copy of the pod repo when you ran `pod install`. Running `pod update` does update the repos first by default.
