### ISSUE TITLE
Feature Request: Different share text per platform

### ISSUE THREAD

**Issue by marcshilling** [BranchMetrics/react-native-branch-deep-linking#9]
It would be great to be able to specify custom share text for each platform. For example:
- If shared to Twitter: "Check out this content! [link] #mybrand @mytwitterhandle"
- If shared to Facebook: "Check out this content! [link]"
- If shared to Email: Subject: "Check out this content!", Body: "This is a description about my content and you can see it by clicking [link]"

Any plans on adding this down the road?

**Comment by rt2zz** [comment]
@marcshilling is this something the iOS native share sheet supports? I cannot find any documentation to that effect.

**Comment by marcshilling** [comment]
I believe it is. Check these out: [iOS](http://www.albertopasca.it/whiletrue/2012/10/objective-c-custom-uiactivityviewcontroller-icons-text/) / [Android](http://stackoverflow.com/questions/9730243/how-to-filter-specific-apps-for-action-send-intent-and-set-a-different-text-for)

**Comment by rt2zz** [comment]
thanks for the links! I believe this feature request actually belongs in the respective [iOS](https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK) / [android](https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK) branch sdk's.

**Comment by marcshilling** [comment]
Hmm, yeah I suppose you're right...although the bridge would need to be updated to be able to pass those strings along from the JS code. Should I open an issue over on those repos?

**Comment by rt2zz** [comment]
@marcshilling did you have a chance to open issues in the upstream repos? I think that would be the best way to source additional discussion and see what is possible.
