### ISSUE TITLE
v1.0.1 breaks XCode 'Archive' of iOS app.

### ISSUE THREAD

**Issue by theseansy** [BranchMetrics/react-native-branch-deep-linking#97]
If you install react-native-branch v1.0.1, XCode's Product -> Archive starts creating 'Generic Xcode Archive' archives instead of iOS App archives.  This is due to the RNBranch.h [having a public header phase in Build Phases](https://developer.apple.com/library/content/technotes/tn2215/_index.html#//apple_ref/doc/uid/DTS40011221-CH1-PROJ). v1.0.0 doesn't have this phase, and Archiving works properly.

![screen shot 2017-02-07 at 11 18 12 am](https://cloud.githubusercontent.com/assets/177857/22707711/83fe9c60-ed28-11e6-90b0-443001dcfad4.png)
![screen shot 2017-02-07 at 11 26 36 am](https://cloud.githubusercontent.com/assets/177857/22707710/83fad4c2-ed28-11e6-9147-4cb2b0ea2064.png)

**Comment by jdee** [comment]
Apologies for the problem. This was fixed in master and just now released as 1.0.2, which also improves peer dependencies. Please let us know if you still have trouble with 1.0.2. Thanks.

**Comment by theseansy** [comment]
Awesome, thanks @jdee

**Comment by theseansy** [comment]
Confirmed new version is fixed
